"use client";

import Link from "next/link";
import {Page,Loading} from "@/components/Page";
import {useData} from "@/components/DataProvider";
import {useLeagueDashboard} from "@/components/useLeagueDashboard";

function MatchupCard({game}:{game:any}){const homeWinner=game.complete&&game.homePoints>game.awayPoints,awayWinner=game.complete&&game.awayPoints>game.homePoints;return <article className="liveMatchup"><header><span>Week {game.week}</span><b>{game.complete?"Final":"Scheduled"}</b></header><div className={homeWinner?"winner":""}><span>#{game.home.powerRank}</span><strong>{game.home.franchise}</strong><small>{game.home.manager}</small><b>{game.complete?game.homePoints.toFixed(1):game.home.power}</b></div><div className={awayWinner?"winner":""}><span>#{game.away.powerRank}</span><strong>{game.away.franchise}</strong><small>{game.away.manager}</small><b>{game.complete?game.awayPoints.toFixed(1):game.away.power}</b></div></article>}

export default function LiveLeague(){
  const {data}=useData(); const {dashboard,loading,power}=useLeagueDashboard(data); if(!data||loading)return <Loading/>;
  if(!dashboard.available)return <Page title="Live League Dashboard" subtitle="The 2026 command center will activate after the first successful Sleeper sync."><section className="liveEmpty"><span>SYNC REQUIRED</span><h2>Connect the live season.</h2><p>Run Sleeper Sync once from Commissioner to populate standings, matchups, activity, and playoff odds.</p><Link href="/commissioner">Open Commissioner →</Link></section></Page>;
  const weekGames=dashboard.matchups.filter((game)=>game.week===dashboard.currentWeek); const leader=dashboard.standings[0];
  return <Page title="Live League Dashboard" subtitle="Standings, weekly matchups, movement, awards, and league activity—automatically refreshed from Sleeper.">
    <section className="liveHero"><div><span className="eyebrow">2026 live control room · Week {dashboard.currentWeek}</span><h2>{leader?.franchise} controls the table.</h2><p>{dashboard.completedWeek?`${dashboard.completedWeek} completed weeks are reflected across every live module.`:"The preseason board is ready. Matchup results will take over after Week 1."}</p><div><span>Leader <b>{leader?.wins}-{leader?.losses}</b></span><span>Points <b>{leader?.points.toFixed(1)}</b></span><span>Power No. <b>{leader?.powerRank}</b></span></div></div><div><span>Playoff race</span><b>6</b><small>teams qualify</small><Link href="/playoff-odds">Run simulator →</Link></div></section>
    <section className="liveAwards">{dashboard.awards.map((award)=><article key={award.label}><span>{award.label}</span><b>{award.value}</b><small>{award.detail}</small></article>)}</section>
    <div className="liveGrid"><section className="livePanel standingsPanel"><header><div><span className="eyebrow">Current table</span><h2>League standings</h2></div><Link href="/playoff-odds">Playoff odds →</Link></header><div className="liveStandings"><div className="tableHead"><span>RK</span><span>TEAM</span><span>REC</span><span>PF</span><span>STRK</span><span>PWR</span></div>{dashboard.standings.map((team,index)=><Link href={`/franchises/${team.franchiseId}`} key={team.franchiseId}><span>{index+1}</span><div><b>{team.franchise}</b><small>{team.manager}</small></div><strong>{team.wins}-{team.losses}{team.ties?`-${team.ties}`:""}</strong><span>{team.points.toFixed(1)}</span><i>{team.streak}</i><em>#{team.powerRank}</em></Link>)}</div></section>
      <section className="livePanel"><header><div><span className="eyebrow">Week {dashboard.currentWeek}</span><h2>{dashboard.completedWeek>=dashboard.currentWeek?"Latest results":"Matchup center"}</h2></div></header><div className="liveMatchups">{weekGames.length?weekGames.map((game)=><MatchupCard game={game} key={game.matchupId}/>):<div className="inlineEmpty">Sleeper has not published this week's matchups yet.</div>}</div></section>
      <section className="livePanel powerPulse"><header><div><span className="eyebrow">Power pulse</span><h2>Top five right now</h2></div><Link href="/power-rankings">Full rankings →</Link></header>{power.slice(0,5).map((team)=><Link href={`/franchises/${team.franchiseId}`} key={team.franchiseId}><span>#{team.rank}</span><div><b>{team.franchise}</b><small>{team.strength.label}</small></div><strong>{team.score}</strong><i className={team.movement>0?"up":team.movement<0?"down":""}>{team.movement>0?`↑${team.movement}`:team.movement<0?`↓${Math.abs(team.movement)}`:"—"}</i></Link>)}</section>
      <section className="livePanel activityPanel"><header><div><span className="eyebrow">League wire</span><h2>Recent activity</h2></div></header>{dashboard.activity.length?<div>{dashboard.activity.map((item,index)=><article key={`${item.time}-${index}`}><span>{item.type}</span><div><b>{item.title}</b><small>{item.detail}</small></div></article>)}</div>:<div className="inlineEmpty">Transactions and trades will appear here as the season moves.</div>}</section>
    </div>
  </Page>;
}
