-- OKFL OS v6.1 — durable Power Rankings generated by each Sleeper sync.
-- Safe to run repeatedly after 001_okfl_schema.sql.

create table if not exists public.power_ranking_snapshots (
  id uuid primary key default gen_random_uuid(),
  league_id text not null references public.leagues(id) on delete cascade,
  season integer not null,
  week integer not null default 0 check (week between 0 and 18),
  phase text not null check (phase in ('preseason','post_draft','regular','playoffs')),
  source_sync_run uuid references public.sync_runs(id) on delete set null,
  model_version text not null,
  synced_at timestamptz not null,
  snapshot jsonb not null,
  created_at timestamptz not null default now(),
  unique (league_id, season, week, phase)
);

create index if not exists power_ranking_snapshots_latest_idx
  on public.power_ranking_snapshots (league_id, season, created_at desc);

alter table public.power_ranking_snapshots enable row level security;
