"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Loading,Page} from "@/components/Page";
import type {TradeWarRoom} from "@/lib/tradeWarRoom";

const windows=["All","Contender","Bubble","Seller"] as const;
export default function TradeWarRoomPage(){const [room,setRoom]=useState<TradeWarRoom|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState<(typeof windows)[number]>("All"),[selected,setSelected]=useState("");useEffect(()=>{fetch("/api/trade-war-room").then(async response=>{const body=await response.json();if(!response.ok||!body.available)throw new Error(body.error||"Run Sleeper Sync to open the War Room.");setRoom(body.warRoom);setSelected(body.warRoom.teams[0]?.franchiseId||"")}).catch(error=>setError(error.message)).finally(()=>setLoading(false))},[]);const teams=useMemo(()=>room?.teams.filter(team=>filter==="All"||team.window===filter)??[],[room,filter]),focus=room?.teams.find(team=>team.franchiseId===selected);if(loading)return <Loading/>;if(!room)return <Page title="Trade Deadline War Room" subtitle="Live roster and playoff intelligence for the stretch run."><section className="liveEmpty"><h2>War Room unavailable.</h2><p>{error}</p><Link href="/commissioner">Open Sleeper Sync →</Link></section></Page>;return <Page title="Trade Deadline War Room" subtitle="Separate contenders from sellers, expose roster pressure points, and find deals that fit both timelines.">
  <section className="warHero"><div><span className="eyebrow">LIVE MARKET · WEEK {room.week||"PRESEASON"}</span><h2>The deadline is a strategy problem.</h2><p>This board combines playoff odds, power rank, positional depth, keeper history, and traded picks. Suggestions identify fit—not automatic fairness—so every proposal still belongs in the Trade Center.</p></div><div className="warMarketPulse"><span>Market split</span><b>{room.teams.filter(t=>t.window==="Contender").length} buyers</b><small>{room.teams.filter(t=>t.window==="Seller").length} likely sellers · {room.deals.length} matched ideas</small></div></section>
  <nav className="warFilters" aria-label="Market filter">{windows.map(value=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{value}<span>{value==="All"?room.teams.length:room.teams.filter(team=>team.window===value).length}</span></button>)}</nav>
  <div className="warLayout"><section className="warBoard"><header><span>TEAM</span><span>WINDOW</span><span>ODDS</span><span>NEEDS</span><span>ASSETS</span></header>{teams.map(team=><button key={team.franchiseId} className={selected===team.franchiseId?"active":""} onClick={()=>setSelected(team.franchiseId)}><div><i>#{team.powerRank}</i><span><b>{team.franchise}</b><small>{team.manager} · {team.record}</small></span></div><em className={team.window.toLowerCase()}>{team.window}</em><strong>{team.playoffOdds.toFixed(1)}%</strong><span>{team.needs.join(" · ")}</span><span>{team.picks.length} picks · {team.keepers.length} keepers</span></button>)}</section>
    {focus&&<aside className="warFocus"><div className="warFocusHead"><span>Selected franchise</span><h2>{focus.franchise}</h2><p>{focus.window} · #{focus.powerRank} power · {focus.playoffOdds.toFixed(1)}% playoff odds</p></div><section><span>Roster diagnosis</span><div className="warTags"><b>Needs</b>{focus.needs.map(row=><i key={row}>{row}</i>)}<b>Surplus</b>{focus.surplus.map(row=><i key={row}>{row}</i>)}</div></section><section><span>Available draft capital</span>{focus.picks.length?<ul>{focus.picks.map(row=><li key={row}>{row}</li>)}</ul>:<p>No tracked premium picks available.</p>}</section><section><span>Keeper assets</span>{focus.keepers.length?<ul>{focus.keepers.map(row=><li key={row.player}><b>{row.player}</b><small>{row.cost}</small></li>)}</ul>:<p>No recent keeper history attached.</p>}</section><section><span>Target list</span>{focus.targets.length?focus.targets.map(row=><div className="warTarget" key={`${row.fromId}-${row.player}`}><b>{row.player}</b><small>{row.position} · from {row.from}</small></div>):<p>No clean need-for-surplus match found.</p>}</section></aside>}
  </div>
  <section className="warDeals"><header><div><span className="eyebrow">Suggested conversations</span><h2>Deals with a reason for both sides</h2></div><Link href="/trades">Open Trade Center →</Link></header><div>{room.deals.map(deal=><article key={deal.id}><div className="warFit"><span>{deal.fit}</span><small>FIT</small></div><p><b>{deal.buyer}</b> targets <strong>{deal.target}</strong> ({deal.position}) from <b>{deal.seller}</b>.</p><em>Starting return: {deal.return}</em><small>{deal.reason}</small><Link href={`/trades?trade=${encodeURIComponent(JSON.stringify({teamA:deal.buyerId,teamB:deal.sellerId,sideA:[{type:"player",player:deal.target,keeperEligible:true}],sideB:[{type:"pick",player:"Draft pick",pickYear:2027,pickRound:Number(deal.return.match(/R(\d+)/)?.[1]||3),keeperEligible:false}],contextA:{window:"contending",needs:[deal.position]},contextB:{window:"retooling",needs:[]}}))}`}>Model this deal →</Link></article>)}</div></section>
  <footer className="warDisclaimer">Roster diagnosis uses current Sleeper depth and league-relative market logic. Confirm injuries, player news, keeper eligibility, and exact pick ownership before making an offer.</footer>
  </Page>}
