"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Loading,Page} from "@/components/Page";
import type {TradeWarRoom} from "@/lib/tradeWarRoom";

const windows=["All","Contender","Bubble","Seller"] as const;
const roundOf=(pick:string)=>Number(pick.match(/\bR(\d+)\b/)?.[1]||99);
const ownPick=(pick:string)=>/^2027 R\d+$/.test(pick);

export default function TradeWarRoomPage(){
  const [room,setRoom]=useState<TradeWarRoom|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filter,setFilter]=useState<(typeof windows)[number]>("All"),[selected,setSelected]=useState("");
  useEffect(()=>{fetch("/api/trade-war-room").then(async response=>{const body=await response.json();if(!response.ok||!body.available)throw new Error(body.error||"Run Sleeper Sync to open the War Room.");setRoom(body.warRoom);setSelected(body.warRoom.teams[0]?.franchiseId||"")}).catch(error=>setError(error.message)).finally(()=>setLoading(false))},[]);
  const teams=useMemo(()=>room?.teams.filter(team=>filter==="All"||team.window===filter)??[],[room,filter]),focus=room?.teams.find(team=>team.franchiseId===selected),preseason=!room?.week;
  const windowLabel=(value:string)=>preseason?`Projected ${value}`:value;
  const capital=focus?focus.picks.filter(pick=>!ownPick(pick)||roundOf(pick)<=5):[],laterOwn=focus?focus.picks.filter(pick=>ownPick(pick)&&roundOf(pick)>5).length:0;
  if(loading)return <Loading/>;
  if(!room)return <Page title="Trade Deadline War Room" subtitle="Live roster and playoff intelligence for the stretch run."><section className="liveEmpty"><h2>War Room unavailable.</h2><p>{error}</p><Link href="/commissioner">Open Sleeper Sync →</Link></section></Page>;
  return <Page title="Trade Deadline War Room" subtitle="Separate contenders from sellers, expose roster pressure points, and find deals that fit both timelines.">
    <section className="deadlineWarHero"><div><span>LIVE MARKET · {room.week?`WEEK ${room.week}`:"PRESEASON MODEL"}</span><h2>The deadline is a strategy problem.</h2><p>This board combines playoff odds, power rank, core-position depth, keeper history, and traded picks. Suggestions identify fit—not automatic fairness—so every proposal still belongs in the Trade Center.</p></div><div className="warMarketPulse"><span>Market split</span><b>{room.teams.filter(team=>team.window==="Contender").length} buyers</b><small>{room.teams.filter(team=>team.window==="Seller").length} likely sellers · {room.deals.length} matched ideas</small></div></section>
    {preseason&&<aside className="warPhaseNote"><b>Preseason projection</b><span>Buyer and seller labels currently use roster power and simulated odds. After Week 1, actual record, scoring, and playoff position take over.</span></aside>}
    <nav className="warFilters" aria-label="Market filter">{windows.map(value=><button key={value} className={filter===value?"active":""} onClick={()=>setFilter(value)}>{preseason&&value!=="All"?`Projected ${value}`:value}<span>{value==="All"?room.teams.length:room.teams.filter(team=>team.window===value).length}</span></button>)}</nav>
    <div className="warLayout"><section className="warBoard"><header><span>TEAM</span><span>WINDOW</span><span>ODDS</span><span>NEEDS</span><span>ASSETS</span></header>{teams.map(team=>{const own=team.picks.filter(ownPick).length,extra=team.picks.length-own;return <button key={team.franchiseId} className={selected===team.franchiseId?"active":""} onClick={()=>setSelected(team.franchiseId)}><div><i>#{team.powerRank}</i><span><b>{team.franchise}</b><small>{team.manager} · {team.record}</small></span></div><em className={team.window.toLowerCase()}>{windowLabel(team.window)}</em><strong>{team.playoffOdds.toFixed(1)}%</strong><span>{team.needs.join(" · ")}</span><span>{own===17?"Full draft":`${own}/17 own picks`}{extra?` + ${extra} acquired`:""} · {team.keepers.length} keepers</span></button>})}</section>
      {focus&&<aside className="warFocus"><div className="warFocusHead"><span>Selected franchise</span><h2>{focus.franchise}</h2><p>{windowLabel(focus.window)} · #{focus.powerRank} power · {focus.playoffOdds.toFixed(1)}% playoff odds</p></div><section><span>Roster diagnosis</span><div className="warTags"><b>Needs</b>{focus.needs.map(row=><i key={row}>{row}</i>)}<b>Surplus</b>{focus.surplus.map(row=><i key={row}>{row}</i>)}</div></section><section><span>Relevant draft capital</span>{capital.length?<ul>{capital.map(row=><li key={row}>{row}</li>)}{laterOwn>0&&<li className="warLaterPicks"><b>Later own picks</b><small>Rounds {18-laterOwn}–17 · {laterOwn} picks</small></li>}</ul>:<p>No tracked premium picks available.</p>}</section><section><span>Keeper assets</span>{focus.keepers.length?<ul>{focus.keepers.map(row=><li key={row.player}><b>{row.player}</b><small>{row.cost}</small></li>)}</ul>:<p>No recent keeper history attached.</p>}</section><section><span>Target list</span>{focus.targets.length?focus.targets.map(row=><div className="warTarget" key={`${row.fromId}-${row.player}`}><b>{row.player}</b><small>{row.position} · from {row.from}</small></div>):<p>No clean, market-supported upgrade found. The model will not force a trade.</p>}</section></aside>}
    </div>
    <section className="warDeals"><header><div><span className="eyebrow">Suggested conversations</span><h2>Deals with a reason for both sides</h2></div><Link href="/trades">Open Trade Center →</Link></header>{room.deals.length?<div>{room.deals.map(deal=><article key={deal.id}><div className="warFit"><span>{deal.fit}</span><small>FIT</small></div><p><b>{deal.buyer}</b> targets <strong>{deal.target}</strong> ({deal.position}) from <b>{deal.seller}</b>.</p><em>Market starting point: {deal.return}</em><small>{deal.reason}</small><Link href={`/trades?trade=${encodeURIComponent(JSON.stringify({teamA:deal.buyerId,teamB:deal.sellerId,sideA:[{type:"player",player:deal.target,keeperEligible:true}],sideB:[{type:"pick",player:"Draft pick",pickYear:2027,pickRound:deal.priceRound,keeperEligible:false}],contextA:{window:"contending",needs:[deal.position]},contextB:{window:"retooling",needs:[]}}))}`}>Model this deal →</Link></article>)}</div>:<div className="warNoDeals"><b>No responsible match right now.</b><p>The model found no market-supported upgrade with a sensible price and willing roster fit. It will refresh after the next Sleeper sync.</p></div>}</section>
    <footer className="warDisclaimer">Roster diagnosis uses current Sleeper depth and league-relative market logic. Confirm injuries, player news, keeper eligibility, and exact pick ownership before making an offer.</footer>
  </Page>;
}
