"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {Loading,Page} from "@/components/Page";
import {useData} from "@/components/DataProvider";
import {useLeagueDashboard} from "@/components/useLeagueDashboard";
import {useAwardsRace} from "@/components/useAwardsRace";
import {useAuth} from "@/components/AuthProvider";
import {RecapArticle} from "@/components/RecapArticle";
import {generateCommissionerRecap,type CommissionerRecap} from "@/lib/commissionerRecap";

export default function WeeklyRecap(){const {data}=useData(),{dashboard,loading,power}=useLeagueDashboard(data),{loading:awardsLoading,awards}=useAwardsRace(),{account}=useAuth();const [selectedWeek,setSelectedWeek]=useState(0),[published,setPublished]=useState<CommissionerRecap|null>(null);const week=selectedWeek||dashboard.completedWeek;useEffect(()=>{if(!week)return;let active=true;fetch(`/api/weekly-recap?week=${week}`).then(r=>r.json()).then(body=>{if(active)setPublished(body.recap||null)}).catch(()=>active&&setPublished(null));return()=>{active=false}},[week]);const automatic=useMemo(()=>dashboard.completedWeek?generateCommissionerRecap(dashboard,awards,power,week):null,[dashboard,awards,power,week]);if(!data||loading||awardsLoading)return <Loading/>;if(!dashboard.available)return <Page title="Weekly League Recap" subtitle="The recap desk activates after the first Sleeper sync."><section className="liveEmpty"><h2>Waiting for live league data.</h2><Link href="/commissioner">Open Commissioner →</Link></section></Page>;if(!dashboard.completedWeek)return <Page title="Weekly League Recap" subtitle="The newsroom opens after Week 1."><section className="recapPreseason"><span className="eyebrow">The newsroom is ready</span><h2>Opening night comes next.</h2><p>Once final scores arrive, the site will build matchup stories, weekly honors, standings movement, and playoff implications.</p></section></Page>;const recap=published||automatic!;return <Page title="Commissioner Recap" subtitle="The official weekly story of the OKFL, built from final results and published by the Commissioner."><section className="recapToolbar"><div><label htmlFor="recap-week">Edition</label><select id="recap-week" value={week} onChange={e=>setSelectedWeek(Number(e.target.value))}>{Array.from({length:dashboard.completedWeek},(_,i)=>i+1).reverse().map(value=><option value={value} key={value}>Week {value}</option>)}</select></div><span className={published?"recapEditionOfficial":"recapEditionAutomatic"}>{published?"Official edition":"Automatic preview"}</span>{account?.role==="commissioner"&&<Link href="/commissioner/recap">Edit & publish →</Link>}</section><RecapArticle recap={recap}/>{!published&&<section className="recapUnpublished"><b>This edition has not been published yet.</b><p>You are seeing the automatic newsroom version generated from final Sleeper results.</p></section>}</Page>}
