"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {useAuth} from "@/components/AuthProvider";

function pct(value:any){return value==null?"—":`${Number(value).toFixed(1)}%`}
function movement(value:number){return value>0?`↑ ${value}`:value<0?`↓ ${Math.abs(value)}`:"—"}

export default function AccountPage(){
  const {account,session,loading,signOut,authFetch}=useAuth();const router=useRouter();
  const [dashboard,setDashboard]=useState<any>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [editing,setEditing]=useState(false);const [profile,setProfile]=useState<any>(null);const [inboxFilter,setInboxFilter]=useState("all");
  async function load(){if(!account||account.mustChangePassword)return;setBusy(true);try{const response=await authFetch("/api/account/franchise-dashboard",{cache:"no-store"});const body=await response.json();if(!response.ok){setMessage(body.error||"Could not load My Franchise.");return}setDashboard(body.dashboard);setProfile(body.dashboard.profile)}catch{setMessage("Could not load My Franchise.")}finally{setBusy(false)}}
  useEffect(()=>{void load()},[account]);
  async function logout(){await signOut();router.replace("/");router.refresh()}
  async function saveProfile(){setBusy(true);setMessage("");try{const response=await authFetch("/api/account/franchise-dashboard",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"profile",profile})});const body=await response.json();if(!response.ok){setMessage(body.error||"Profile update failed.");return}setEditing(false);setMessage("Manager profile and team branding saved.");await load()}finally{setBusy(false)}}
  async function markRead(id?:string){await authFetch("/api/account/franchise-dashboard",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(id?{action:"read",id}:{action:"read-all"})});await load()}
  if(loading)return <div className="card loadingCard"><span/>Loading franchise command center…</div>;
  if(!session||!account)return <section className="accountGate card"><span className="eyebrow">Manager access</span><h1>Sign in to your franchise.</h1><p>Your private dashboard connects live roster, matchup, keeper, trade, awards, and career intelligence.</p><Link href="/login?next=/account">Open account login</Link></section>;
  if(account.mustChangePassword)return <section className="accountGate card"><span className="eyebrow">Action required</span><h1>Create your private password.</h1><p>Your temporary password must be replaced before My Franchise is available.</p><Link href="/account/change-password?next=/account">Change password now</Link></section>;
  if(!dashboard)return <section className="accountGate card"><span className="eyebrow">My Franchise</span><h1>{busy?"Building your dashboard…":"Dashboard setup required."}</h1><p>{message||"Loading roster, matchup, rankings, awards, and career intelligence."}</p>{message.includes("migration 007")&&<code>supabase/007_manager_franchise_hub.sql</code>}</section>;

  const {season,career}=dashboard;const metric=career.metric||{};const inboxItems=(dashboard.inbox.items||[]).filter((row:any)=>inboxFilter==="all"||row.kind===inboxFilter);
  const starters=dashboard.roster.filter((row:any)=>row.starter),bench=dashboard.roster.filter((row:any)=>!row.starter);
  const heroStyle={"--mf-primary":dashboard.profile.primaryColor,"--mf-accent":dashboard.profile.accentColor} as React.CSSProperties;
  return <div className="myFranchise" style={heroStyle}>
    <section className="mfHero"><div className="mfIdentity"><div className="mfAvatar">{dashboard.profile.avatarUrl?<img src={dashboard.profile.avatarUrl} alt={`${account.displayName} avatar`}/>:<span>{account.displayName.slice(0,2).toUpperCase()}</span>}</div><div><span className="eyebrow">My Franchise · {account.franchiseId}</span><h1>{dashboard.profile.teamDisplayName}</h1><h2>{account.displayName} · {account.role==="commissioner"?"Commissioner & Manager":"League Manager"}</h2><p>{dashboard.profile.bio||"Add a manager bio and make this franchise page your own."}</p>{dashboard.profile.motto&&<blockquote>“{dashboard.profile.motto}”</blockquote>}</div></div><div className="mfHeroActions"><button onClick={()=>setEditing((value)=>!value)}>{editing?"Close editor":"Edit profile"}</button><Link href={`/franchises/${account.franchiseId}`}>Public scouting report</Link>{account.role==="commissioner"&&<Link href="/commissioner">Commissioner OS</Link>}</div></section>

    {editing&&<section className="mfProfileEditor"><header><div><span className="eyebrow">Manager identity</span><h2>Profile & team branding</h2></div><small>Changes are tied permanently to {account.franchiseId}.</small></header><div className="mfProfileFields"><label><span>Team display name</span><input value={profile.teamDisplayName} maxLength={50} onChange={(event)=>setProfile({...profile,teamDisplayName:event.target.value})}/></label><label><span>Avatar URL</span><input value={profile.avatarUrl} placeholder="https://…" onChange={(event)=>setProfile({...profile,avatarUrl:event.target.value})}/></label><label><span>Primary color</span><input type="color" value={profile.primaryColor} onChange={(event)=>setProfile({...profile,primaryColor:event.target.value})}/></label><label><span>Accent color</span><input type="color" value={profile.accentColor} onChange={(event)=>setProfile({...profile,accentColor:event.target.value})}/></label><label className="wide"><span>Manager bio</span><textarea maxLength={280} value={profile.bio} onChange={(event)=>setProfile({...profile,bio:event.target.value})} placeholder="How do you run your franchise?"/></label><label className="wide"><span>Team motto</span><input maxLength={100} value={profile.motto} onChange={(event)=>setProfile({...profile,motto:event.target.value})} placeholder="The line your rivals should remember."/></label></div><footer><button className="secondaryButton" onClick={()=>{setProfile(dashboard.profile);setEditing(false)}}>Cancel</button><button onClick={saveProfile} disabled={busy}>Save profile</button></footer></section>}
    {message&&<p className="mfMessage" role="status">{message}</p>}

    <section className="mfPulse"><article><span>Career record</span><b>{metric.wins||0}–{metric.losses||0}</b><small>{Number(metric.win_pct||0).toFixed(1)}% win rate</small></article><article><span>2026 standing</span><b>{season.standing?`${season.standing.wins}–${season.standing.losses}`:"Preseason"}</b><small>{season.standing?`${season.standing.points.toFixed(1)} points for`:"Waiting for Sleeper"}</small></article><article><span>Playoff probability</span><b>{pct(season.odds?.playoff)}</b><small>{pct(season.odds?.champion)} championship</small></article><article><span>Power ranking</span><b>{season.power?`#${season.power.rank}`:"—"}</b><small>{season.power?`${movement(season.power.movement)} · ${season.power.score} power`:"Sync required"}</small></article><article><span>Inbox</span><b>{dashboard.inbox.unread}</b><small>Unread offers, polls & alerts</small></article></section>

    <div className="mfPrimaryGrid">
      <section className="mfPanel mfMatchup"><header><div><span className="eyebrow">Week {season.matchup?.week||season.currentWeek}</span><h2>Upcoming matchup</h2></div><Link href="/live-league">League dashboard →</Link></header>{season.matchup?<div className="mfVersus"><article><span>You</span><b>{dashboard.profile.teamDisplayName}</b><strong>#{season.matchup.myTeam.powerRank}</strong><small>{season.matchup.myTeam.wins}–{season.matchup.myTeam.losses} · {season.matchup.myTeam.points.toFixed(1)} PF</small></article><i>VS</i><article><span>Opponent</span><b>{season.matchup.opponent.franchise}</b><strong>#{season.matchup.opponent.powerRank}</strong><small>{season.matchup.opponent.wins}–{season.matchup.opponent.losses} · {season.matchup.opponent.points.toFixed(1)} PF</small></article></div>:<div className="mfEmpty">No upcoming synced matchup yet.</div>}</section>
      <section className="mfPanel mfOdds"><header><div><span className="eyebrow">Personal simulation</span><h2>Your playoff path</h2></div><Link href="/playoff-odds">Full simulator →</Link></header><div className="mfOddsRing" style={{"--odds":`${season.odds?.playoff||0}%`} as React.CSSProperties}><b>{pct(season.odds?.playoff)}</b><span>Make playoffs</span></div><div className="mfOddsStats"><div><span>Projected wins</span><b>{season.odds?.projectedWins?.toFixed(1)||"—"}</b></div><div><span>First-round bye</span><b>{pct(season.odds?.bye)}</b></div><div><span>No. 1 seed</span><b>{pct(season.odds?.first)}</b></div><div><span>Win title</span><b>{pct(season.odds?.champion)}</b></div></div></section>
    </div>

    <div className="mfContentGrid">
      <section className="mfPanel mfRoster"><header><div><span className="eyebrow">Sleeper roster</span><h2>My team</h2></div><b>{dashboard.roster.length} players</b></header><h3>Starting lineup</h3><div className="mfPlayerList">{starters.map((player:any)=><article key={player.id}><span className={`mfPos ${player.position}`}>{player.position}</span><div><b>{player.name}</b><small>{player.team}</small></div><strong>{player.latestPoints.toFixed(1)}</strong></article>)}{!starters.length&&<p>No synced starting lineup yet.</p>}</div><details><summary>Bench · {bench.length}</summary><div className="mfPlayerList">{bench.map((player:any)=><article key={player.id}><span className={`mfPos ${player.position}`}>{player.position}</span><div><b>{player.name}</b><small>{player.team}</small></div><strong>{player.latestPoints.toFixed(1)}</strong></article>)}</div></details></section>
      <div className="mfStack"><section className="mfPanel"><header><div><span className="eyebrow">Keeper lab</span><h2>Recommendations</h2></div><Link href="/keepers">Manage →</Link></header><div className="mfKeeperRows">{dashboard.keepers.recommendations.map((row:any,index:number)=><article key={`${row.player}-${index}`}><span>0{index+1}</span><div><b>{row.player}</b><small>{row.position} · {row.status}</small></div><strong>R{row.round}</strong></article>)}</div></section><section className="mfPanel"><header><div><span className="eyebrow">Front-office scan</span><h2>Trade needs</h2></div><Link href="/trades">Trade Center →</Link></header><div className="mfNeeds">{dashboard.trade.needs.map((need:any)=><div key={need.position}><span>{need.position}</span><i><b style={{width:`${Math.min(100,need.count/need.target*100)}%`}}/></i><strong>{need.count}/{need.target}</strong></div>)}</div><h3>Potential targets</h3><div className="mfTargets">{dashboard.trade.targets.map((target:any)=><div key={target.id}><span>{target.position}</span><b>{target.name}</b><small>{target.franchise} · Rank {target.rank}</small></div>)}{!dashboard.trade.targets.length&&<p>Roster balance looks healthy.</p>}</div></section></div>
    </div>

    <div className="mfContentGrid mfLower">
      <section className="mfPanel mfInbox"><header><div><span className="eyebrow">Private franchise inbox</span><h2>Offers, polls & notifications</h2></div>{dashboard.inbox.unread>0&&<button onClick={()=>markRead()}>Mark all read</button>}</header><div className="mfInboxTabs">{[["all","All",dashboard.inbox.unread],["offer","Offers",dashboard.inbox.counts.offers],["poll","Polls",dashboard.inbox.counts.polls],["notification","Alerts",dashboard.inbox.counts.notifications]].map(([key,label,count]:any)=><button key={key} className={inboxFilter===key?"active":""} onClick={()=>setInboxFilter(key)}>{label}<b>{count}</b></button>)}</div><div className="mfInboxList">{inboxItems.map((item:any)=><article key={item.id} className={item.read?"read":"unread"}><i>{item.kind.slice(0,1).toUpperCase()}</i><div><span>{item.kind}</span><b>{item.title}</b><p>{item.body}</p><small>{new Date(item.createdAt).toLocaleString()}</small></div><div>{item.href&&<Link href={item.href}>Open</Link>}{!item.read&&<button onClick={()=>markRead(item.id)}>Mark read</button>}</div></article>)}{!inboxItems.length&&<div className="mfEmpty">Nothing in this inbox yet.</div>}</div></section>
      <section className="mfPanel"><header><div><span className="eyebrow">Awards & rankings</span><h2>Your league movement</h2></div><Link href="/league-awards">Awards race →</Link></header>{season.power&&<article className="mfPowerCard"><div><span>Power rank</span><b>#{season.power.rank}</b></div><strong className={season.power.movement>0?"up":season.power.movement<0?"down":""}>{movement(season.power.movement)}</strong><p>{season.power.summary}</p></article>}<div className="mfAwardRows">{dashboard.awards.rows.slice(0,6).map((row:any)=><article key={row.key}><span>#{row.rank}</span><div><b>{row.title}</b><small>{row.detail}</small></div><strong>{row.score}</strong></article>)}{!dashboard.awards.rows.length&&<div className="mfEmpty">Awards candidacy begins after synced games.</div>}</div></section>
    </div>

    <section className="mfLegacy"><header><div><span className="eyebrow">Manager profile & achievements</span><h2>Career headquarters</h2></div><div><b>{metric.championships||0}</b><span>Titles</span><b>{metric.runner_ups||0}</b><span>Finals losses</span><b>{metric.legacy_score||0}</b><span>Legacy score</span></div></header><div className="mfLegacyGrid"><section><h3>Trophy case</h3><div className="mfTrophies">{career.badges.map((badge:any)=><article key={badge.key} className={badge.tone}><i>{badge.icon}</i><div><b>{badge.title}</b><small>{badge.detail}</small></div></article>)}</div></section><section><h3>Primary rivalries</h3><div className="mfRivalries">{career.rivalries.map((rival:any,index:number)=><article key={rival.franchiseId}><span>0{index+1}</span><div><b>{rival.franchise}</b><small>{rival.games} meetings · closest {rival.closest.toFixed(2)} pts</small></div><strong>{rival.wins}–{rival.losses}</strong></article>)}</div></section><section><h3>Final finishes</h3><div className="mfFinishChart">{career.finishes.map((finish:any)=><div key={finish.season}><span>{finish.season}</span><i><b style={{height:`${Math.max(12,(11-finish.finish)*9)}%`}}/></i><strong>#{finish.finish}</strong></div>)}</div></section></div></section>

    <section className="mfPanel mfActivity"><header><div><span className="eyebrow">Account history</span><h2>Personal activity</h2></div><button className="secondaryButton" onClick={logout}>Sign out</button></header><div>{dashboard.activity.map((item:any)=><article key={item.id}><i/><span>{item.type}</span><div><b>{item.title}</b><small>{item.detail}</small></div><time>{item.createdAt?new Date(item.createdAt).toLocaleDateString():"—"}</time></article>)}</div><footer><Link href="/account/change-password">Change password</Link></footer></section>
  </div>;
}
