"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {useAuth} from "@/components/AuthProvider";
import {calendarCategories,type CalendarCategory,type LeagueCalendarEvent} from "@/lib/leagueCalendar";

type Draft={id:string;title:string;description:string;category:CalendarCategory;startsAt:string;endsAt:string;allDay:boolean;href:string};
const empty:Draft={id:"",title:"",description:"",category:"league",startsAt:"",endsAt:"",allDay:false,href:""};
const localInput=(value:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):"";

export function CommissionerCalendar(){
  const {authFetch}=useAuth();const [events,setEvents]=useState<LeagueCalendarEvent[]>([]),[draft,setDraft]=useState<Draft>(empty),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[migrationRequired,setMigrationRequired]=useState(false);
  async function load(){setLoading(true);const response=await authFetch("/api/commissioner/calendar",{cache:"no-store"}),body=await response.json();if(response.ok){setEvents(body.events||[]);setMigrationRequired(false)}else{setMessage(body.error||"Calendar controls unavailable.");setMigrationRequired(Boolean(body.migrationRequired))}setLoading(false)}
  useEffect(()=>{void load()},[]);
  async function request(payload:any,key:string){setBusy(key);setMessage("");const response=await authFetch("/api/commissioner/calendar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),body=await response.json();setBusy("");setMessage(response.ok?(payload.action==="notify"?`Reminder added to ${body.recipients} inboxes${body.queued?` and queued on ${body.queued} device${body.queued===1?"":"s"}`:""}.`:payload.action==="delete"?"Event deleted.":"Calendar event published."):body.error||"Calendar action failed.");if(response.ok){setDraft(empty);await load()}return response.ok}
  function edit(event:LeagueCalendarEvent){setDraft({id:event.id,title:event.title,description:event.description,category:event.category,startsAt:localInput(event.startsAt),endsAt:localInput(event.endsAt),allDay:event.allDay,href:event.href});window.scrollTo({top:0,behavior:"smooth"})}
  if(loading)return <div className="card loadingCard"><span/>Loading Calendar Controls…</div>;
  if(migrationRequired)return <section className="settingsMigration card"><span className="eyebrow">One-time database step</span><h1>Activate the league calendar</h1><p>{message}</p><code>supabase/013_league_calendar.sql</code><button onClick={load}>Check again</button><Link href="/commissioner">Return to Commissioner OS</Link></section>;
  return <div className="calendarAdmin"><header className="calendarAdminHero"><div><span className="eyebrow">Commissioner-only scheduling</span><h1>Calendar Controls</h1><p>Publish official league dates and send an immediate reminder to every manager’s OKFL inbox and enabled device.</p></div><Link href="/calendar">View public calendar</Link></header>{message&&<div className="calendarMessage">{message}</div>}
    <div className="calendarAdminLayout"><form onSubmit={event=>{event.preventDefault();void request({action:"save",...draft,startsAt:new Date(draft.startsAt).toISOString(),endsAt:draft.endsAt?new Date(draft.endsAt).toISOString():null},"save")}}><span className="eyebrow">{draft.id?"Edit official event":"New official event"}</span><h2>{draft.id?"Update event":"Add to league calendar"}</h2><label>Event title<input required minLength={3} maxLength={100} value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})} placeholder="2026 OKFL Draft"/></label><div className="calendarFormRow"><label>Category<select value={draft.category} onChange={event=>setDraft({...draft,category:event.target.value as CalendarCategory})}>{calendarCategories.map(category=><option key={category} value={category}>{category[0].toUpperCase()+category.slice(1)}</option>)}</select></label><label className="allDayToggle"><input type="checkbox" checked={draft.allDay} onChange={event=>setDraft({...draft,allDay:event.target.checked})}/><span>All-day event</span></label></div><div className="calendarFormRow"><label>Starts<input required type="datetime-local" value={draft.startsAt} onChange={event=>setDraft({...draft,startsAt:event.target.value})}/></label><label>Ends (optional)<input type="datetime-local" value={draft.endsAt} onChange={event=>setDraft({...draft,endsAt:event.target.value})}/></label></div><label>Description<textarea rows={5} maxLength={1000} value={draft.description} onChange={event=>setDraft({...draft,description:event.target.value})} placeholder="What managers need to know…"/></label><label>Optional OKFL link<input value={draft.href} onChange={event=>setDraft({...draft,href:event.target.value})} placeholder="/live-draft"/></label><button disabled={busy==="save"}>{busy==="save"?"Publishing…":draft.id?"Update event":"Publish event"}</button>{draft.id&&<button type="button" className="calendarSecondary" onClick={()=>setDraft(empty)}>Cancel editing</button>}</form>
      <section className="calendarAdminList"><header><div><span className="eyebrow">Published schedule</span><h2>{events.length} managed events</h2></div><Link href="/calendar">Open calendar</Link></header>{events.map(event=><article key={event.id} className={event.category}><time><b>{new Date(event.startsAt).getDate()}</b><span>{new Date(event.startsAt).toLocaleString("en-US",{month:"short",year:"numeric"})}</span></time><div><span>{event.category}</span><h3>{event.title}</h3><p>{new Date(event.startsAt).toLocaleString()} {event.description&&`· ${event.description}`}</p></div><footer><button onClick={()=>edit(event)}>Edit</button><button disabled={busy===`notify-${event.id}`} onClick={()=>request({action:"notify",id:event.id},`notify-${event.id}`)}>{busy===`notify-${event.id}`?"Sending…":"Notify league"}</button><button className="danger" onClick={()=>window.confirm(`Delete “${event.title}”?`)&&request({action:"delete",id:event.id},`delete-${event.id}`)}>Delete</button></footer></article>)}{!events.length&&<div className="calendarEmpty"><b>No managed events yet</b><p>Keeper deadlines and ballot closings still appear automatically on the public calendar.</p></div>}</section></div>
  </div>;
}
