"use client";

import {useEffect,useState} from "react";
import {useAuth} from "@/components/AuthProvider";

type Contact={userId:string;franchiseId:string;franchise:string;displayName:string;username:string;phone:string;smsOptedIn:boolean;consentConfirmedAt:string|null;pushDevices:number};
type Communication={id:string;kind:"announcement"|"poll";title:string;body:string;status:string;closes_at:string|null;created_at:string;recipientCount:number;totalVotes:number;results:Array<{id:string;label:string;votes:number}>;push:{queued:number;failed:number;notEnabled:number;notConfigured:number};sms:{queued:number;failed:number;notConsented:number;notConfigured:number}};

export function CommissionerCommunications(){
  const {authFetch}=useAuth();const [contacts,setContacts]=useState<Contact[]>([]),[history,setHistory]=useState<Communication[]>([]),[smsConfigured,setSmsConfigured]=useState(false),[pushConfigured,setPushConfigured]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
  const [kind,setKind]=useState<"announcement"|"poll">("announcement"),[title,setTitle]=useState(""),[body,setBody]=useState(""),[choices,setChoices]=useState(["",""]),[closesAt,setClosesAt]=useState(""),[sendSms,setSendSms]=useState(false),[recipients,setRecipients]=useState<string[]>([]);
  async function load(){setLoading(true);const response=await authFetch("/api/commissioner/communications",{cache:"no-store"});const result=await response.json();if(response.ok){setContacts(result.contacts||[]);setHistory(result.communications||[]);setSmsConfigured(Boolean(result.smsConfigured));setPushConfigured(Boolean(result.pushConfigured));setRecipients((current)=>current.length?current:(result.contacts||[]).map((row:Contact)=>row.userId));}else setMessage(result.error||"Communications setup is incomplete.");setLoading(false);}
  useEffect(()=>{void load()},[]);
  const editContact=(userId:string,patch:Partial<Contact>)=>setContacts((current)=>current.map((row)=>row.userId===userId?{...row,...patch}:row));
  async function saveContact(contact:Contact){setBusy(`contact-${contact.userId}`);setMessage("");const response=await authFetch("/api/commissioner/communications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"contact",userId:contact.userId,phone:contact.phone,smsOptedIn:contact.smsOptedIn,consentConfirmed:contact.smsOptedIn})});const result=await response.json();setBusy("");if(!response.ok){setMessage(result.error||"Contact could not be saved.");return}editContact(contact.userId,{phone:result.phone||"",smsOptedIn:Boolean(result.smsOptedIn),consentConfirmedAt:result.consentConfirmedAt});setMessage(`${contact.displayName}'s contact settings were saved.`);}
  const toggleRecipient=(userId:string)=>setRecipients((current)=>current.includes(userId)?current.filter((id)=>id!==userId):[...current,userId]);
  async function publish(event:React.FormEvent){event.preventDefault();setBusy("publish");setMessage("");const response=await authFetch("/api/commissioner/communications",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,title,body,choices,closesAt:closesAt||null,sendSms,recipientUserIds:recipients})});const result=await response.json();setBusy("");if(!response.ok){setMessage(result.error||"Message could not be published.");return}setTitle("");setBody("");setChoices(["",""]);setClosesAt("");setSendSms(false);setMessage(`Published to ${result.recipients} franchise${result.recipients===1?"":"s"} · ${result.push.queued} free push alert${result.push.queued===1?"":"s"}${sendSms?` · ${result.sms.queued} texts queued`:""}.`);await load();}
  async function closePoll(id:string){setBusy(`close-${id}`);const response=await authFetch("/api/commissioner/communications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"close",communicationId:id})});const result=await response.json();setBusy("");if(!response.ok){setMessage(result.error||"Poll could not be closed.");return}setMessage("Ballot closed. Final results are locked.");await load();}
  if(loading)return <section className="commHub commLoading"><span className="eyebrow">League communications</span><h2>Opening the commissioner newsroom…</h2></section>;
  return <section className="commHub">
    <header className="commHubHead"><div><span className="eyebrow">New · Commissioner newsroom</span><h2>Announcements & league votes</h2><p>Publish to every manager’s private inbox, run authenticated one-franchise-one-vote ballots, and automatically notify every installed OKFL device for free.</p></div><div className={pushConfigured?"smsState ready":"smsState"}><i/><span>{pushConfigured?"Free push connected":"In-site delivery ready"}</span><small>{pushConfigured?"Installed devices alert automatically":"Finish Firebase setup to enable phone alerts"}</small></div></header>
    {message&&<div className="commMessage" role="status">{message}</div>}
    <div className="commWorkspace">
      <form className="commComposer" onSubmit={publish}><div className="commSectionTitle"><span>01</span><div><b>Compose</b><small>Everyone receives an in-site notification.</small></div></div><div className="commKind"><button type="button" className={kind==="announcement"?"active":""} onClick={()=>setKind("announcement")}>Announcement</button><button type="button" className={kind==="poll"?"active":""} onClick={()=>setKind("poll")}>League vote</button></div><label>Headline<input required maxLength={120} value={title} onChange={(event)=>setTitle(event.target.value)} placeholder={kind==="poll"?"Vote on the 2027 rule change":"Draft date is officially set"}/></label><label>Message<textarea maxLength={2000} value={body} onChange={(event)=>setBody(event.target.value)} placeholder="Give managers the details…"/></label>
        {kind==="poll"&&<div className="commOptions"><span>Ballot choices</span>{choices.map((choice,index)=><div key={index}><input required value={choice} onChange={(event)=>setChoices((current)=>current.map((item,itemIndex)=>itemIndex===index?event.target.value:item))} placeholder={`Option ${index+1}`}/>{choices.length>2&&<button type="button" onClick={()=>setChoices((current)=>current.filter((_,itemIndex)=>itemIndex!==index))} aria-label={`Remove option ${index+1}`}>×</button>}</div>)}{choices.length<8&&<button type="button" onClick={()=>setChoices((current)=>[...current,""])}>+ Add choice</button>}<label>Voting closes <input type="datetime-local" value={closesAt} onChange={(event)=>setClosesAt(event.target.value)}/></label></div>}
        <fieldset className="commRecipients"><legend>Recipients <button type="button" onClick={()=>setRecipients(recipients.length===contacts.length?[]:contacts.map((row)=>row.userId))}>{recipients.length===contacts.length?"Clear all":"Select all"}</button></legend>{contacts.map((contact)=><label key={contact.userId}><input type="checkbox" checked={recipients.includes(contact.userId)} onChange={()=>toggleRecipient(contact.userId)}/><span>{contact.displayName}<small>{contact.franchise}</small></span><i className={contact.pushDevices?"smsYes":""}>{contact.pushDevices?`PUSH ${contact.pushDevices}`:"INBOX"}</i></label>)}</fieldset>
        <label className={smsConfigured?"commSmsToggle":"commSmsToggle disabled"}><input type="checkbox" checked={sendSms} disabled={!smsConfigured} onChange={(event)=>setSendSms(event.target.checked)}/><span><b>Also send by text message</b><small>{smsConfigured?"Only opted-in managers with a saved number will be texted.":"Configure Twilio in Vercel to unlock SMS delivery."}</small></span></label><button className="commPublish" disabled={busy==="publish"||!recipients.length}>{busy==="publish"?"Publishing…":kind==="poll"?"Open league vote":"Send announcement"}</button>
      </form>
      <div className="commDirectory"><div className="commSectionTitle"><span>02</span><div><b>Phone directory</b><small>Private · visible only to the Commissioner.</small></div></div><p className="consentNote">Only enable SMS after the manager explicitly agrees to OKFL texts. Standard message rates may apply; managers can reply STOP.</p><div className="contactList">{contacts.map((contact)=><article key={contact.userId}><header><span>{contact.franchiseId}</span><div><b>{contact.displayName}</b><small>{contact.franchise}</small></div></header><label>Mobile number<input inputMode="tel" value={contact.phone} onChange={(event)=>editContact(contact.userId,{phone:event.target.value})} placeholder="+1 212 555 0100"/></label><label className="contactConsent"><input type="checkbox" checked={contact.smsOptedIn} onChange={(event)=>editContact(contact.userId,{smsOptedIn:event.target.checked})}/><span>Manager consented to SMS</span></label><button type="button" onClick={()=>saveContact(contact)} disabled={busy===`contact-${contact.userId}`}>{busy===`contact-${contact.userId}`?"Saving…":"Save contact"}</button></article>)}</div></div>
    </div>
    <div className="commHistory"><div className="commSectionTitle"><span>03</span><div><b>Delivery & voting history</b><small>One permanent record for every send.</small></div></div>{history.length?<div className="commHistoryList">{history.map((item)=><article key={item.id}><header><span className={`commType ${item.kind}`}>{item.kind}</span><time>{new Date(item.created_at).toLocaleString()}</time>{item.kind==="poll"&&item.status==="open"&&<button onClick={()=>closePoll(item.id)} disabled={busy===`close-${item.id}`}>Close vote</button>}</header><h3>{item.title}</h3><p>{item.body}</p><div className="commStats"><span><b>{item.recipientCount}</b> inboxes</span><span><b>{item.push.queued}</b> pushes</span>{item.sms.queued>0&&<span><b>{item.sms.queued}</b> texts</span>}{item.kind==="poll"&&<span><b>{item.totalVotes}</b> votes</span>}</div>{item.results?.length>0&&<div className="commResults">{item.results.map((option)=><div key={option.id}><span>{option.label}</span><i><em style={{width:`${item.totalVotes?option.votes/item.totalVotes*100:0}%`}}/></i><b>{option.votes}</b></div>)}</div>}</article>)}</div>:<div className="commEmpty">Your first announcement or ballot will appear here.</div>}</div>
  </section>;
}
