"use client";

import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {useAuth} from "@/components/AuthProvider";
import {useData} from "@/components/DataProvider";
import type {ManagedRule,PublicLeagueSettings} from "@/lib/leagueSettings";

type Manager={userId:string;franchiseId:string;displayName:string;franchise:string;devices:number;lastSeenAt:string|null;platforms:string[]};
type Tab="overview"|"rules"|"league"|"notifications";
const emptyRule:ManagedRule={id:"",category:"League",rule:"",status:"draft",sortOrder:0,updatedAt:null};

export function CommissionerSettings(){
  const {authFetch}=useAuth();const {data,loadData}=useData({lazy:true});
  const [tab,setTab]=useState<Tab>("overview"),[settings,setSettings]=useState<PublicLeagueSettings|null>(null),[rules,setRules]=useState<ManagedRule[]>([]),[managers,setManagers]=useState<Manager[]>([]),[pushConfigured,setPushConfigured]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[migrationRequired,setMigrationRequired]=useState(false),[editing,setEditing]=useState<ManagedRule>(emptyRule),[query,setQuery]=useState("");
  async function load(clearMessage=true){setLoading(true);if(clearMessage)setMessage("");const response=await authFetch("/api/commissioner/settings",{cache:"no-store"});const body=await response.json();if(response.ok){setSettings(body.settings);setRules(body.rules||[]);setManagers(body.managers||[]);setPushConfigured(Boolean(body.pushConfigured));setMigrationRequired(false)}else{setMessage(body.error||"Settings could not be loaded.");setMigrationRequired(Boolean(body.migrationRequired))}setLoading(false)}
  useEffect(()=>{void load();void loadData()},[]);
  const published=rules.filter((rule)=>rule.status==="published").length,drafts=rules.length-published,enabled=managers.filter((manager)=>manager.devices>0).length;
  const visibleRules=useMemo(()=>{const term=query.trim().toLowerCase();return rules.filter((rule)=>!term||`${rule.id} ${rule.category} ${rule.rule}`.toLowerCase().includes(term))},[rules,query]);
  async function request(body:any,label:string,busyKey=label){setBusy(busyKey);setMessage("");const response=await authFetch("/api/commissioner/settings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();setBusy("");setMessage(response.ok?label==="seed"?`${result.count} official rules imported.`:label==="test"?`Test delivered to ${result.sent} device${result.sent===1?"":"s"}.`:"Saved successfully.":result.error||"Action failed.");if(response.ok)await load(false);return response.ok}
  async function saveSettings(){if(!settings)return;setBusy("settings");setMessage("");const response=await authFetch("/api/commissioner/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});const result=await response.json();setBusy("");setMessage(response.ok?"League settings are live.":result.error||"Settings could not be saved.");if(response.ok){setSettings(result.settings);window.dispatchEvent(new CustomEvent("okfl:settings-updated",{detail:result.settings}))}}
  async function saveRule(){if(!rules.length){setMessage("Import the current official rulebook before creating the first managed rule.");return}const ok=await request({action:"save-rule",...editing},"rule");if(ok)setEditing(emptyRule)}
  async function deleteRule(rule:ManagedRule){if(!window.confirm(`Delete ${rule.id}? This removes it from the managed rulebook.`))return;await request({action:"delete-rule",id:rule.id},"delete")}
  async function importRules(){const official=data?.rules||[];if(!official.length){setMessage("The official archive is still loading. Try again in a moment.");return}await request({action:"seed-rules",rules:official},"seed")}
  if(loading)return <div className="card loadingCard"><span/>Loading Commissioner settings…</div>;
  if(migrationRequired)return <section className="settingsMigration card"><span className="eyebrow">One-time database step</span><h1>Activate website-managed settings</h1><p>{message}</p><code>supabase/011_commissioner_settings.sql</code><button onClick={()=>load()}>Check again</button><Link href="/commissioner">Return to Commissioner OS</Link></section>;
  if(!settings)return <section className="card emptyState"><h2>Settings unavailable</h2><p>{message}</p><button onClick={()=>load()}>Retry</button></section>;
  return <div className="commissionerSettingsPage">
    <header className="settingsHero"><div><span className="eyebrow">Commissioner-only administration</span><h1>League Settings</h1><p>Change the rulebook, publish league-wide notices, verify notification enrollment, and jump to operational controls without editing code.</p></div><Link href="/commissioner">Commissioner OS</Link></header>
    <nav className="settingsTabs" aria-label="Commissioner settings sections">{([['overview','Overview'],['rules','Rulebook'],['league','League notice'],['notifications','Notifications']] as Array<[Tab,string]>).map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</nav>
    {message&&<div className="settingsMessage" role="status">{message}</div>}
    {tab==="overview"&&<><section className="settingsStats"><button onClick={()=>setTab("rules")}><span>Published rules</span><b>{published}</b><small>{drafts} draft{drafts===1?"":"s"}</small></button><button onClick={()=>setTab("notifications")}><span>Push enrollment</span><b>{enabled}/{managers.length}</b><small>{managers.length-enabled} manager{managers.length-enabled===1?"":"s"} left</small></button><button onClick={()=>setTab("league")}><span>League notice</span><b>{settings.noticeActive?"Live":"Off"}</b><small>Rulebook v{settings.rulebookVersion}</small></button></section><section className="settingsQuickGrid"><article><span>Communications</span><h2>Announcements & votes</h2><p>Create ballots, inspect named votes, and send league updates.</p><Link href="/commissioner#league-comms">Open communications</Link></article><article><span>Keeper operations</span><h2>Deadline & final board</h2><p>Set the keeper deadline, review submissions, and lock the official board.</p><Link href="/commissioner#keeper-operations">Open keeper controls</Link></article><article><span>Draft operations</span><h2>Official live room</h2><p>Create the league draft, control the clock, and manage the live room.</p><Link href="/live-draft">Open Live Draft</Link></article><article><span>League health</span><h2>Sync & audit trail</h2><p>Sync Sleeper, repair identities, and review recorded Commissioner actions.</p><Link href="/commissioner#league-operations">Open league health</Link></article></section></>}
    {tab==="rules"&&<section className="settingsRuleLayout"><aside className="ruleEditor"><span className="eyebrow">{editing.id?`Editing ${editing.id}`:"Create a rule"}</span><h2>{editing.id?"Update rule":"New rule"}</h2><label>Rule ID<input value={editing.id} disabled={Boolean(editing.updatedAt)} onChange={(event)=>setEditing({...editing,id:event.target.value.toUpperCase()})} placeholder="LG-003"/></label><label>Category<input value={editing.category} onChange={(event)=>setEditing({...editing,category:event.target.value})} placeholder="League"/></label><label>Rule text<textarea value={editing.rule} onChange={(event)=>setEditing({...editing,rule:event.target.value})} rows={6} placeholder="Write the complete official rule…"/></label><div className="ruleEditorRow"><label>Status<select value={editing.status} onChange={(event)=>setEditing({...editing,status:event.target.value as "draft"|"published"})}><option value="draft">Draft</option><option value="published">Published</option></select></label><label>Order<input type="number" min="0" value={editing.sortOrder} onChange={(event)=>setEditing({...editing,sortOrder:Number(event.target.value)})}/></label></div><button onClick={saveRule} disabled={busy==="rule"}>{busy==="rule"?"Saving…":"Save rule"}</button>{editing.id&&<button className="settingsSecondary" onClick={()=>setEditing(emptyRule)}>Cancel editing</button>}{!rules.length&&<button className="settingsImport" onClick={importRules} disabled={busy==="seed"}>{busy==="seed"?"Importing…":"Import current official rulebook"}</button>}<small>Draft rules are visible only here. Published rules replace the static public rulebook.</small></aside><div className="managedRules"><header><div><span className="eyebrow">Managed constitution</span><h2>{rules.length} rules</h2></div><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Search rules…"/></header>{visibleRules.map((rule)=><article key={rule.id} className={rule.status}><div><span>{rule.id}</span><i>{rule.status}</i></div><h3>{rule.category}</h3><p>{rule.rule}</p><footer><small>{rule.updatedAt?`Updated ${new Date(rule.updatedAt).toLocaleString()}`:"Not published yet"}</small><button onClick={()=>setEditing(rule)}>Edit</button><button onClick={()=>deleteRule(rule)}>Delete</button></footer></article>)}{!rules.length&&<div className="settingsEmpty"><h3>No managed rules yet</h3><p>Import the existing rulebook once, then every future change can be made here.</p></div>}</div></section>}
    {tab==="league"&&<section className="leagueSettingsPanel"><div><span className="eyebrow">Public league notice</span><h2>Control the banner every manager sees</h2><p>Use this for deadlines, draft instructions, rule changes, or anything that should stay visible across the website.</p></div><label className="noticeToggle"><input type="checkbox" checked={settings.noticeActive} onChange={(event)=>setSettings({...settings,noticeActive:event.target.checked})}/><span><b>Show league notice</b><small>Turn this off to hide it without deleting the message.</small></span></label><label>Notice title<input value={settings.noticeTitle} maxLength={80} onChange={(event)=>setSettings({...settings,noticeTitle:event.target.value})} placeholder="Keeper deadline approaching"/></label><label>Message<textarea rows={4} maxLength={300} value={settings.noticeBody} onChange={(event)=>setSettings({...settings,noticeBody:event.target.value})} placeholder="Keepers lock Friday at 8:00 PM…"/></label><div className="leagueSettingsRow"><label>Optional OKFL link<input value={settings.noticeHref} onChange={(event)=>setSettings({...settings,noticeHref:event.target.value})} placeholder="/keepers"/></label><label>Rulebook version<input value={settings.rulebookVersion} onChange={(event)=>setSettings({...settings,rulebookVersion:event.target.value})} placeholder="2026.1"/></label></div><button onClick={saveSettings} disabled={busy==="settings"}>{busy==="settings"?"Publishing…":"Save league settings"}</button>{settings.noticeActive&&<div className="noticePreview"><span>Preview</span><b>{settings.noticeTitle||"League notice"}</b><p>{settings.noticeBody||"Your message will appear here."}</p></div>}</section>}
    {tab==="notifications"&&<section className="notificationAdmin"><header><div><span className="eyebrow">Member devices</span><h2>Push activation tracker</h2><p>See who is ready for app alerts and send a safe test to enabled members.</p></div><span className={pushConfigured?"ready":"notReady"}>{pushConfigured?"Firebase ready":"Firebase not configured"}</span></header><div className="notificationManagerList">{managers.map((manager)=><article key={manager.userId} className={manager.devices?"enabled":"missing"}><span>{manager.franchiseId}</span><div><b>{manager.displayName}</b><small>{manager.franchise}</small></div><strong>{manager.devices?`${manager.devices} device${manager.devices===1?"":"s"}`:"Not enabled"}</strong><small>{manager.lastSeenAt?`Seen ${new Date(manager.lastSeenAt).toLocaleDateString()}`:"No registered device"}</small><button disabled={!manager.devices||!pushConfigured||busy===`test-${manager.userId}`} onClick={()=>request({action:"test-push",userId:manager.userId},"test",`test-${manager.userId}`)}>{busy===`test-${manager.userId}`?"Sending…":"Send test"}</button></article>)}</div></section>}
  </div>;
}
