"use client";

import Link from "next/link";
import {Loading,Page} from "@/components/Page";
import {useAwardsRace} from "@/components/useAwardsRace";

function PlayerRace({race,final}:{race:any;final:boolean}){const leader=race.candidates[0];return <section className="awardRace"><header><div><span className="eyebrow">{final?"Final award":"Live award race"}</span><h2>{race.title}</h2><p>{race.subtitle}</p></div>{leader&&<div className="awardLeader"><span>{final?"WINNER":"LEADER"}</span><b>{leader.name}</b><small>{leader.points.toFixed(1)} points · {leader.franchise}</small></div>}</header><div className="awardPlayerRows">{race.candidates.length?race.candidates.slice(0,6).map((player:any)=><article key={player.playerId}><span>{player.rank}</span><div><b>{player.name}</b><small>{player.position} · {player.team} · {player.franchise}</small></div><div><i><b style={{width:`${player.score}%`}}/></i></div><strong>{player.points.toFixed(1)}</strong><em>{player.weeklyAverage.toFixed(1)} AVG</em></article>):<div className="awardEmpty">This race activates when eligible players record points.</div>}</div></section>}
function ManagerRace({race,final}:{race:any;final:boolean}){return <section className="managerRace"><header><div><span className="eyebrow">{final?"Final selection":"Manager ladder"}</span><h2>{race.title}</h2><p>{race.subtitle}</p></div></header>{race.candidates.slice(0,5).map((manager:any)=><Link href={`/franchises/${manager.franchiseId}`} key={manager.franchiseId}><span>{manager.rank}</span><div><b>{manager.manager}</b><small>{manager.franchise} · {manager.record} · Power #{manager.powerRank}</small></div><div className="managerFactors">{manager.dimensions.map((item:any)=><i key={item.label} title={`${item.label}: ${item.score}`}><b style={{width:`${item.score}%`}}/></i>)}</div><strong>{manager.score}</strong></Link>)}</section>}

export default function LeagueAwards(){const {loading,awards}=useAwardsRace();if(loading)return <Loading/>;if(!awards)return <Page title="League Awards Race" subtitle="Awards will activate after the next successful Sleeper sync."><section className="liveEmpty"><h2>Waiting for live league data.</h2><Link href="/commissioner">Open Commissioner →</Link></section></Page>;return <Page title={awards.final?"2026 OKFL Award Winners":"2026 League Awards Race"} subtitle={awards.final?"The season is complete and the final winners are locked.":`Updated weekly from Sleeper results through Week ${awards.throughWeek}.`}>
  <section className={awards.final?"awardsHero final":"awardsHero"}><div><span className="eyebrow">{awards.final?"The final ballot":"The season-long ballot"}</span><h2>{awards.final?"The 2026 winners are official.":"Every week reshapes the race."}</h2><p>Player awards use actual Sleeper scoring from players on OKFL rosters. Manager awards combine results, scoring, live power, consistency, roster strength, and activity.</p></div><div><span>Season status</span><b>{awards.final?"FINAL":`WEEK ${awards.throughWeek}`}</b><small>{awards.final?"Winners selected":"Rankings remain live"}</small></div></section>
  <div className="awardsSectionHead"><div><span className="eyebrow">Player honors</span><h2>On-field award ladders</h2></div><Link href="/weekly-recap">Open weekly recap →</Link></div><div className="playerRaceGrid">{awards.playerRaces.map((race)=><PlayerRace key={race.key} race={race} final={awards.final}/>)}</div>
  <div className="awardsSectionHead"><div><span className="eyebrow">Front office honors</span><h2>Manager and GM rankings</h2></div><span>Scores shown on a 100-point index</span></div><div className="managerRaceGrid">{awards.managerRaces.map((race)=><ManagerRace key={race.key} race={race} final={awards.final}/>)}</div>
  <section className="awardMethod"><span className="eyebrow">How winners are selected</span><div><article><b>Players</b><p>Actual Sleeper player points accumulated in completed OKFL matchups. Waiver honors require a completed waiver or free-agent transaction.</p></article><article><b>Managers</b><p>Manager of the Year emphasizes wins and scoring. GM of the Year emphasizes roster power, scoring, transactions, and overall results.</p></article><article><b>Final lock</b><p>All races update weekly. After the championship portion of the schedule, the top-ranked candidate becomes the official winner.</p></article></div></section>
  </Page>}
