import type {PowerRanking} from "./powerRankings";
import type {LeagueDashboard,LiveStanding} from "./liveLeague";

export type AwardPlayer={rank:number;playerId:string;name:string;position:string;team:string;franchiseId:string|null;franchise:string;points:number;weeklyAverage:number;games:number;score:number};
export type ManagerCandidate={rank:number;franchiseId:string;franchise:string;manager:string;score:number;record:string;points:number;powerRank:number;dimensions:Array<{label:string;score:number}>;reason:string};
export type AwardsRace={season:number;throughWeek:number;final:boolean;syncedAt:string|null;playerRaces:Array<{key:string;title:string;subtitle:string;candidates:AwardPlayer[]}>;managerRaces:Array<{key:string;title:string;subtitle:string;candidates:ManagerCandidate[]}>;weeklyLeaders:Record<string,AwardPlayer[]>};

function percentile(values:number[],value:number){const sorted=[...values].sort((a,b)=>a-b);if(!sorted.length)return 50;const below=sorted.filter((row)=>row<value).length,equal=sorted.filter((row)=>row===value).length;return Math.round((below+equal*.5)/sorted.length*100);}
function nameOf(player:any,id:string){return player?.full_name||[player?.first_name,player?.last_name].filter(Boolean).join(" ")||`Player ${id}`;}
function rankPlayers(rows:Omit<AwardPlayer,"rank"|"score">[],limit=8){const max=Math.max(1,...rows.map((row)=>row.points));return rows.sort((a,b)=>b.points-a.points||b.weeklyAverage-a.weeklyAverage).slice(0,limit).map((row,index)=>({...row,rank:index+1,score:Math.round(row.points/max*100)}));}

export function buildAwardsRace(snapshot:any,directory:Record<string,any>,power:PowerRanking[],dashboard:LeagueDashboard):AwardsRace{
  const completedRows=(snapshot?.matchups??[]).filter((row:any)=>row.franchise_id&&Number(row.points)>0);
  const throughWeek=dashboard.completedWeek; const final=throughWeek>=17;
  const rosterToFranchise=new Map<string,string>(),ownerByPlayer=new Map<string,string>();
  for(const roster of snapshot?.rosters??[]){if(!roster.franchise_id)continue;rosterToFranchise.set(String(roster.roster_id),roster.franchise_id);for(const id of roster.players??[])ownerByPlayer.set(String(id),roster.franchise_id);}
  for(const draft of snapshot?.drafts??[])for(const pick of draft.picks??draft.raw?.picks??[]){const id=String(pick.player_id??pick.metadata?.player_id??"");if(id&&!ownerByPlayer.has(id)&&pick.franchise_id)ownerByPlayer.set(id,pick.franchise_id);}
  const franchiseNames=new Map(dashboard.standings.map((team)=>[team.franchiseId,team.franchise]));
  const totals=new Map<string,{points:number;weeks:Set<number>}>(),weekly=new Map<number,Map<string,number>>();
  for(const row of completedRows){const week=Number(row.week);const map=weekly.get(week)??new Map<string,number>();for(const [id,value] of Object.entries(row.players_points??{})){const points=Number(value??0);if(!Number.isFinite(points))continue;map.set(id,(map.get(id)??0)+points);const total=totals.get(id)??{points:0,weeks:new Set<number>()};total.points+=points;total.weeks.add(week);totals.set(id,total);}weekly.set(week,map);}
  const playerRows=[...totals.entries()].filter(([id])=>Boolean(directory[id])).map(([id,total]):Omit<AwardPlayer,"rank"|"score">=>{const player=directory[id]??{};const franchiseId=ownerByPlayer.get(id)??null;return {playerId:id,name:nameOf(player,id),position:String(player.position??"FLEX"),team:String(player.team??"FA"),franchiseId,franchise:franchiseId?franchiseNames.get(franchiseId)??franchiseId:"Free agent",points:Math.round(total.points*10)/10,weeklyAverage:Math.round(total.points/Math.max(1,total.weeks.size)*10)/10,games:total.weeks.size};});
  const addedIds=new Set<string>();for(const tx of snapshot?.transactions??[])if(tx.status==="complete"&&(tx.type==="waiver"||tx.type==="free_agent"))for(const add of tx.adds??[])addedIds.add(String(add.player_id));
  const playerRaces=[
    {key:"mvp",title:"OKFL Most Valuable Player",subtitle:"All-position scoring leader across completed OKFL weeks",candidates:rankPlayers([...playerRows])},
    {key:"skill",title:"Offensive Player of the Year",subtitle:"Top running back, receiver, or tight end",candidates:rankPlayers(playerRows.filter((row)=>["RB","WR","TE"].includes(row.position)))},
    {key:"quarterback",title:"Quarterback of the Year",subtitle:"The strongest season at the league's premium position",candidates:rankPlayers(playerRows.filter((row)=>row.position==="QB"))},
    {key:"waiver",title:"Waiver Find of the Year",subtitle:"The best scoring player acquired through waivers or free agency",candidates:rankPlayers(playerRows.filter((row)=>addedIds.has(row.playerId)))},
  ];
  const weeklyLeaders:Record<string,AwardPlayer[]>={};for(const [week,map] of weekly){const rows=[...map.entries()].filter(([id])=>Boolean(directory[id])).map(([id,points]):Omit<AwardPlayer,"rank"|"score">=>{const player=directory[id]??{},franchiseId=ownerByPlayer.get(id)??null;return {playerId:id,name:nameOf(player,id),position:String(player.position??"FLEX"),team:String(player.team??"FA"),franchiseId,franchise:franchiseId?franchiseNames.get(franchiseId)??franchiseId:"Free agent",points:Math.round(points*10)/10,weeklyAverage:Math.round(points*10)/10,games:1};});weeklyLeaders[String(week)]=rankPlayers(rows,5);}

  const powerById=new Map(power.map((team)=>[team.franchiseId,team]));const winPcts=dashboard.standings.map((team)=>team.wins/Math.max(1,team.wins+team.losses+team.ties)),points=dashboard.standings.map((team)=>team.points);
  const transactionCounts=new Map<string,number>();for(const tx of snapshot?.transactions??[])for(const id of tx.roster_ids??[]){const franchiseId=rosterToFranchise.get(String(id));if(franchiseId)transactionCounts.set(franchiseId,(transactionCounts.get(franchiseId)??0)+1);}
  const managerBase=dashboard.standings.map((team)=>{const ranking=powerById.get(team.franchiseId),winPct=team.wins/Math.max(1,team.wins+team.losses+team.ties),recordScore=percentile(winPcts,winPct),pointsScore=percentile(points,team.points),powerScore=ranking?.score??50,consistency=Math.max(0,100-Math.abs((ranking?.rank??team.powerRank)-(dashboard.standings.indexOf(team)+1))*12),activity=Math.min(100,35+(transactionCounts.get(team.franchiseId)??0)*8);return {team,ranking,recordScore,pointsScore,powerScore,consistency,activity};});
  const makeManagers=(key:"manager"|"gm")=>managerBase.map(({team,ranking,recordScore,pointsScore,powerScore,consistency,activity})=>{const dimensions=key==="manager"?[{label:"Results",score:recordScore},{label:"Scoring",score:pointsScore},{label:"Power",score:powerScore},{label:"Consistency",score:consistency}]:[{label:"Roster power",score:powerScore},{label:"Scoring",score:pointsScore},{label:"Activity",score:activity},{label:"Results",score:recordScore}];const weights=key==="manager"?[.4,.25,.2,.15]:[.4,.25,.15,.2];const score=Math.round(dimensions.reduce((sum,item,index)=>sum+item.score*weights[index],0));const strongest=[...dimensions].sort((a,b)=>b.score-a.score)[0];return {franchiseId:team.franchiseId,franchise:team.franchise,manager:team.manager,score,record:`${team.wins}-${team.losses}${team.ties?`-${team.ties}`:""}`,points:team.points,powerRank:ranking?.rank??team.powerRank,dimensions,reason:`${strongest.label} is the strongest part of the case so far.`};}).sort((a,b)=>b.score-a.score||b.points-a.points).map((row,index)=>({...row,rank:index+1}));
  const managerRaces=[{key:"manager",title:"Manager of the Year",subtitle:"Weekly results, scoring, power, and consistency",candidates:makeManagers("manager")},{key:"gm",title:"General Manager of the Year",subtitle:"Roster strength, scoring, activity, and results",candidates:makeManagers("gm")}];
  return {season:2026,throughWeek,final,syncedAt:snapshot?.synced_at??null,playerRaces,managerRaces,weeklyLeaders};
}
