import type {OKFLData} from "@/lib/types";
import type {LeagueDashboard,PlayoffOdds} from "@/lib/liveLeague";
import type {PowerRanking} from "@/lib/powerRankings";

export type WarRoomTeam={franchiseId:string;franchise:string;manager:string;window:"Contender"|"Bubble"|"Seller";playoffOdds:number;powerRank:number;record:string;needs:string[];surplus:string[];targets:Array<{player:string;position:string;from:string;fromId:string}>;picks:string[];keepers:Array<{player:string;cost:string}>};
export type WarRoomDeal={id:string;buyer:string;buyerId:string;seller:string;sellerId:string;target:string;position:string;return:string;reason:string;fit:number};
export type TradeWarRoom={season:number;week:number;teams:WarRoomTeam[];deals:WarRoomDeal[];updatedAt:string|null};

const rosterSlots:Record<string,number>={QB:1,RB:2,WR:2,TE:1,K:1,DEF:1};
function playerName(directory:Record<string,any>,id:string){const p=directory[id]||{};return p.full_name||[p.first_name,p.last_name].filter(Boolean).join(" ")||`Player ${id}`}
function position(directory:Record<string,any>,id:string){return String(directory[id]?.position||"FLEX").toUpperCase()}

export function buildTradeWarRoom(data:OKFLData,snapshot:any,dashboard:LeagueDashboard,power:PowerRanking[],odds:PlayoffOdds[],directory:Record<string,any>):TradeWarRoom{
  const powerById=new Map(power.map((row)=>[row.franchiseId,row]));const oddsById=new Map(odds.map((row)=>[row.franchiseId,row]));
  const rosterById=new Map((snapshot?.rosters??[]).filter((row:any)=>row.franchise_id).map((row:any)=>[row.franchise_id,row]));
  const ownerByRoster=new Map<string,string>((snapshot?.rosters??[]).map((row:any):[string,string]=>[String(row.roster_id),String(row.franchise_id||"")]));
  const picksById=new Map<string,string[]>();for(const team of dashboard.standings)picksById.set(team.franchiseId,["2027 R1","2027 R2","2027 R3"]);
  for(const pick of snapshot?.traded_picks??[]){const current=ownerByRoster.get(String(pick.owner_id)),original=ownerByRoster.get(String(pick.roster_id));if(!current||!original||current===original)continue;const label=`${pick.season||2027} R${pick.round} (${dashboard.standings.find((x)=>x.franchiseId===original)?.franchise||original})`;picksById.set(current,[...(picksById.get(current)||[]),label]);picksById.set(original,(picksById.get(original)||[]).filter((row)=>!row.startsWith(`${pick.season||2027} R${pick.round}`)));}
  const teams:WarRoomTeam[]=dashboard.standings.map((standing)=>{const roster=rosterById.get(standing.franchiseId) as any;const players=(roster?.players??[]).map(String).filter((id:string)=>directory[id]);const counts=new Map<string,number>();for(const id of players){const pos=position(directory,id);counts.set(pos,(counts.get(pos)||0)+1)}const needs=Object.entries(rosterSlots).filter(([pos,min])=>(counts.get(pos)||0)<min+1).map(([pos])=>pos);const surplus=Object.entries(rosterSlots).filter(([pos,min])=>(counts.get(pos)||0)>min+2).map(([pos])=>pos);const chance=oddsById.get(standing.franchiseId)?.playoff??Math.max(5,100-standing.powerRank*8);const window=chance>=68||standing.powerRank<=3?"Contender":chance<=32&&standing.powerRank>=7?"Seller":"Bubble";const keepers=data.keepers.filter((row:any)=>row.franchise_id===standing.franchiseId&&Number(row.season)>=2025).slice(-3).map((row:any)=>({player:row.player,cost:String(row.cost||"TBD")}));return {franchiseId:standing.franchiseId,franchise:standing.franchise,manager:standing.manager,window,playoffOdds:Math.round(chance*10)/10,powerRank:powerById.get(standing.franchiseId)?.rank??standing.powerRank,record:`${standing.wins}-${standing.losses}`,needs:needs.length?needs:["Depth"],surplus:surplus.length?surplus:[players.length>12?"Depth":"None"],targets:[],picks:picksById.get(standing.franchiseId)||[],keepers};});
  const byId=new Map(teams.map((row)=>[row.franchiseId,row]));for(const buyer of teams){const targets:Array<{player:string;position:string;from:string;fromId:string}>=[];for(const seller of teams.filter((row)=>row.franchiseId!==buyer.franchiseId&&(row.window==="Seller"||buyer.window!=="Seller"))){const roster=rosterById.get(seller.franchiseId) as any;for(const id of (roster?.players??[]).map(String)){const pos=position(directory,id);if(buyer.needs.includes(pos)&&seller.surplus.includes(pos))targets.push({player:playerName(directory,id),position:pos,from:seller.franchise,fromId:seller.franchiseId});}}buyer.targets=targets.slice(0,4)}
  const deals:WarRoomDeal[]=[];for(const buyer of teams.filter((row)=>row.window!=="Seller")){for(const target of buyer.targets.slice(0,2)){const seller=byId.get(target.fromId)!;const pick=buyer.picks.find((row)=>/R[1-4]/.test(row))||"future mid-round pick";deals.push({id:`${buyer.franchiseId}-${target.fromId}-${target.player}`,buyer:buyer.franchise,buyerId:buyer.franchiseId,seller:seller.franchise,sellerId:seller.franchiseId,target:target.player,position:target.position,return:pick,reason:`${target.player} attacks ${buyer.franchise}'s ${target.position} need while ${seller.franchise} converts depth into flexible keeper-era capital.`,fit:Math.max(62,94-Math.abs(buyer.powerRank-seller.powerRank)*3)})}}
  return {season:2026,week:dashboard.completedWeek,teams:teams.sort((a,b)=>a.powerRank-b.powerRank),deals:deals.sort((a,b)=>b.fit-a.fit).slice(0,10),updatedAt:snapshot?.synced_at??null};
}
