import type {OKFLData} from "@/lib/types";
import type {LeagueDashboard,PlayoffOdds} from "@/lib/liveLeague";
import type {PowerRanking} from "@/lib/powerRankings";

export type WarRoomTarget={player:string;position:string;from:string;fromId:string};
export type WarRoomTeam={franchiseId:string;franchise:string;manager:string;window:"Contender"|"Bubble"|"Seller";playoffOdds:number;powerRank:number;record:string;needs:string[];surplus:string[];targets:WarRoomTarget[];picks:string[];keepers:Array<{player:string;cost:string}>};
export type WarRoomDeal={id:string;buyer:string;buyerId:string;seller:string;sellerId:string;target:string;position:string;return:string;priceRound:number;marketRank:number|null;reason:string;fit:number};
export type TradeWarRoom={season:number;week:number;teams:WarRoomTeam[];deals:WarRoomDeal[];updatedAt:string|null};
export type WarRoomMarketPlayer={name:string;position:string;pprRank:number;keeperEligible?:boolean};

// Kicker and defense shortages are draft/waiver decisions, not deadline trade needs.
const rosterSlots:Record<string,number>={QB:1,RB:2,WR:3,TE:1};
function playerName(directory:Record<string,any>,id:string){const p=directory[id]||{};return p.full_name||[p.first_name,p.last_name].filter(Boolean).join(" ")||`Player ${id}`}
function position(directory:Record<string,any>,id:string){return String(directory[id]?.position||"FLEX").toUpperCase()}
function playerKey(value:string){return value.normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/\b(jr|sr|ii|iii|iv)\b/g,"").replace(/[^a-z0-9]/g,"")}
function keeperRound(value:string){const match=String(value||"").match(/\d+/);return match?Number(match[0]):null}

export function recommendPickRound(rank:number|null,keeperSurplus=0){
  if(!rank)return 10;
  const adjusted=Math.max(1,rank-Math.max(0,keeperSurplus)*5);
  if(adjusted<=12)return 1;if(adjusted<=28)return 2;if(adjusted<=45)return 3;if(adjusted<=65)return 4;
  if(adjusted<=85)return 5;if(adjusted<=105)return 6;if(adjusted<=130)return 7;if(adjusted<=155)return 8;return 10;
}

export function buildTradeWarRoom(data:OKFLData,snapshot:any,dashboard:LeagueDashboard,power:PowerRanking[],odds:PlayoffOdds[],directory:Record<string,any>,market:WarRoomMarketPlayer[]=[]):TradeWarRoom{
  const powerById=new Map(power.map(row=>[row.franchiseId,row])),oddsById=new Map(odds.map(row=>[row.franchiseId,row]));
  const marketByName=new Map(market.map(row=>[playerKey(row.name),row]));
  const rankOf=(id:string)=>marketByName.get(playerKey(playerName(directory,id)))?.pprRank??999;
  const rosterById=new Map((snapshot?.rosters??[]).filter((row:any)=>row.franchise_id).map((row:any)=>[row.franchise_id,row]));
  const ownerByRoster=new Map<string,string>((snapshot?.rosters??[]).map((row:any):[string,string]=>[String(row.roster_id),String(row.franchise_id||"")]));
  const picksById=new Map<string,string[]>();for(const team of dashboard.standings)picksById.set(team.franchiseId,Array.from({length:17},(_,index)=>`2027 R${index+1}`));
  for(const pick of snapshot?.traded_picks??[]){const current=ownerByRoster.get(String(pick.owner_id)),original=ownerByRoster.get(String(pick.roster_id));if(!current||!original||current===original)continue;const round=Number(pick.round),year=Number(pick.season)||2027,label=`${year} R${round} (${dashboard.standings.find(x=>x.franchiseId===original)?.franchise||original})`;picksById.set(current,[...(picksById.get(current)||[]),label]);picksById.set(original,(picksById.get(original)||[]).filter(row=>row!==`${year} R${round}`));}
  const rosterPlayersById=new Map<string,string[]>();
  const teams:WarRoomTeam[]=dashboard.standings.map(standing=>{const roster=rosterById.get(standing.franchiseId) as any,players=(roster?.players??[]).map(String).filter((id:string)=>directory[id]);rosterPlayersById.set(standing.franchiseId,players);const counts=new Map<string,number>();for(const id of players){const pos=position(directory,id);counts.set(pos,(counts.get(pos)||0)+1)}const needs=Object.entries(rosterSlots).filter(([pos,min])=>(counts.get(pos)||0)<min+1).map(([pos])=>pos),surplus=Object.entries(rosterSlots).filter(([pos,min])=>(counts.get(pos)||0)>min+2).map(([pos])=>pos),chance=oddsById.get(standing.franchiseId)?.playoff??Math.max(5,100-standing.powerRank*8),window=chance>=68||standing.powerRank<=3?"Contender":chance<=32&&standing.powerRank>=7?"Seller":"Bubble",keepers=data.keepers.filter((row:any)=>row.franchise_id===standing.franchiseId&&Number(row.season)>=2025).slice(-3).map((row:any)=>({player:row.player,cost:String(row.cost||"TBD")}));return {franchiseId:standing.franchiseId,franchise:standing.franchise,manager:standing.manager,window,playoffOdds:Math.round(chance*10)/10,powerRank:powerById.get(standing.franchiseId)?.rank??standing.powerRank,record:`${standing.wins}-${standing.losses}`,needs:needs.length?needs:["Depth"],surplus:surplus.length?surplus:[players.length>12?"Depth":"None"],targets:[],picks:picksById.get(standing.franchiseId)||[],keepers};});
  type Candidate=WarRoomTarget&{playerId:string;rank:number;upgrade:number};const candidatesByBuyer=new Map<string,Candidate[]>();
  for(const buyer of teams){const candidates:Candidate[]=[],buyerPlayers=rosterPlayersById.get(buyer.franchiseId)||[];for(const need of buyer.needs.filter(row=>row!=="Depth")){const currentBest=Math.min(999,...buyerPlayers.filter(id=>position(directory,id)===need).map(rankOf));for(const seller of teams.filter(row=>row.franchiseId!==buyer.franchiseId&&(row.window==="Seller"||buyer.window==="Contender"))){if(!seller.surplus.includes(need))continue;const atPosition=(rosterPlayersById.get(seller.franchiseId)||[]).filter(id=>position(directory,id)===need).sort((a,b)=>rankOf(a)-rankOf(b));const sellable=atPosition.slice(Math.max(1,rosterSlots[need]||1));for(const id of sellable){const rank=rankOf(id),upgrade=currentBest-rank;if(rank>=999||currentBest<999&&upgrade<12)continue;candidates.push({player:playerName(directory,id),playerId:id,position:need,from:seller.franchise,fromId:seller.franchiseId,rank,upgrade})}}}candidates.sort((a,b)=>b.upgrade-a.upgrade||a.rank-b.rank);candidatesByBuyer.set(buyer.franchiseId,candidates);buyer.targets=candidates.slice(0,4).map(({player,position:pos,from,fromId})=>({player,position:pos,from,fromId}))}
  const byId=new Map(teams.map(row=>[row.franchiseId,row])),deals:WarRoomDeal[]=[],sellerUses=new Map<string,number>(),usedPlayers=new Set<string>();
  for(const buyer of teams.filter(row=>row.window!=="Seller")){const target=(candidatesByBuyer.get(buyer.franchiseId)||[]).find(row=>(sellerUses.get(row.fromId)||0)<2&&!usedPlayers.has(row.player));if(!target)continue;const seller=byId.get(target.fromId)!;const keeper=seller.keepers.find(row=>playerKey(row.player)===playerKey(target.player)),cost=keeperRound(keeper?.cost||""),expected=Math.ceil(target.rank/10),keeperSurplus=cost?Math.max(0,cost-expected):0,priceRound=recommendPickRound(target.rank,keeperSurplus),pick=buyer.picks.find(row=>new RegExp(`R${priceRound}(?:\\s|$|\\()`).test(row));if(!pick)continue;const fit=Math.round(Math.max(60,Math.min(96,68+Math.min(18,target.upgrade/2)+(buyer.window==="Contender"?6:0)-(priceRound<=2&&keeperSurplus===0?8:0))));deals.push({id:`${buyer.franchiseId}-${target.fromId}-${target.player}`,buyer:buyer.franchise,buyerId:buyer.franchiseId,seller:seller.franchise,sellerId:seller.franchiseId,target:target.player,position:target.position,return:pick,priceRound,marketRank:target.rank,reason:`${target.player} is a real ${target.position} upgrade for ${buyer.franchise} (PPR rank ${target.rank}), while a Round ${priceRound} return matches the player's market tier${keeperSurplus>0?` plus Round ${cost} keeper surplus`:" without charging an undocumented keeper premium"}.`,fit});sellerUses.set(target.fromId,(sellerUses.get(target.fromId)||0)+1);usedPlayers.add(target.player)}
  return {season:2026,week:dashboard.completedWeek,teams:teams.sort((a,b)=>a.powerRank-b.powerRank),deals:deals.sort((a,b)=>b.fit-a.fit).slice(0,8),updatedAt:snapshot?.synced_at??null};
}
