"use client";

import {useEffect,useState} from "react";
import {useAuth} from "@/components/AuthProvider";
import {disableFirebasePush,enableFirebasePush,firebaseBrowserIsConfigured} from "@/lib/firebaseClient";

type Device={installationId:string;deviceLabel:string;platform:string;lastSeenAt:string};
const isIos=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
const isStandalone=()=>window.matchMedia("(display-mode: standalone)").matches||Boolean((navigator as any).standalone);
const deviceLabel=()=>{const mobile=/mobile|iphone|ipad|android/i.test(navigator.userAgent);return `${mobile?"Phone":"Computer"} · ${navigator.platform||"Web"}`.slice(0,80)};

export function NotificationSetup(){
  const {authFetch}=useAuth();const [devices,setDevices]=useState<Device[]>([]),[serverReady,setServerReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[installReady,setInstallReady]=useState(false),[standalone,setStandalone]=useState(false);
  async function load(){const response=await authFetch("/api/account/push",{cache:"no-store"});const result=await response.json();if(response.ok){setDevices(result.devices||[]);setServerReady(Boolean(result.configured));}else setMessage(result.error||"Notification setup is not available yet.");}
  useEffect(()=>{setStandalone(isStandalone());setInstallReady(Boolean(window.okflInstallPrompt));const ready=()=>setInstallReady(true);window.addEventListener("okfl:install-ready",ready);void load();return()=>window.removeEventListener("okfl:install-ready",ready);},[]);
  async function saveFid(installationId:string){const response=await authFetch("/api/account/push",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({installationId,deviceLabel:deviceLabel(),platform:isIos()?"ios":/android/i.test(navigator.userAgent)?"android":"desktop"})});const result=await response.json();if(!response.ok)throw new Error(result.error||"Device registration failed.");}
  async function removeFid(installationId:string){await authFetch("/api/account/push",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({installationId})});}
  async function enable(){setBusy(true);setMessage("");try{if(isIos()&&!isStandalone())throw new Error("On iPhone, first tap Share → Add to Home Screen, then open OKFL OS from the new icon.");await enableFirebasePush(saveFid,removeFid);setMessage("This device will now receive free OKFL announcements and vote alerts.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Notifications could not be enabled.");}finally{setBusy(false)}}
  async function disable(){setBusy(true);setMessage("");try{await disableFirebasePush();await authFetch("/api/account/push",{method:"DELETE",headers:{"Content-Type":"application/json"},body:"{}"});setDevices([]);setMessage("Notifications were disabled for your registered devices.");}catch(error){setMessage(error instanceof Error?error.message:"Notifications could not be disabled.");}finally{setBusy(false)}}
  async function install(){const prompt=window.okflInstallPrompt;if(!prompt)return;await prompt.prompt();await prompt.userChoice;window.okflInstallPrompt=undefined;setInstallReady(false);setStandalone(isStandalone());}
  const supported=typeof window!=="undefined"&&"Notification" in window&&"serviceWorker" in navigator;const configured=serverReady&&firebaseBrowserIsConfigured();
  return <section className="mfPanel pushSetup"><header><div><span className="eyebrow">Pocket league</span><h2>App & phone alerts</h2></div><span className={devices.length?"pushStatus active":"pushStatus"}><i/>{devices.length?`${devices.length} device${devices.length===1?"":"s"} on`:"Not enabled"}</span></header><p>Install OKFL OS on your home screen and get Commissioner announcements and league-vote alerts without text-message fees.</p><div className="pushActions">{installReady&&!standalone&&<button type="button" className="secondaryButton" onClick={install}>Install OKFL OS</button>}<button type="button" onClick={enable} disabled={busy||!supported||!configured}>{busy?"Working…":devices.length?"Add this device":"Enable free alerts"}</button>{devices.length>0&&<button type="button" className="pushDisable" onClick={disable} disabled={busy}>Turn off</button>}</div>{!configured&&<small className="pushHelp">Push is built in but needs the one-time Firebase and Vercel setup in the release guide.</small>}{isIos()&&!standalone&&<small className="pushHelp">iPhone: Safari → Share → Add to Home Screen. Open the installed app, then enable alerts.</small>}{!supported&&<small className="pushHelp">This browser does not support web push. Try current Safari, Chrome, Edge, or Firefox.</small>}{message&&<div className="pushMessage" role="status">{message}</div>}{devices.length>0&&<div className="pushDevices">{devices.map((device)=><span key={device.installationId}><i/> {device.deviceLabel}<small>Seen {new Date(device.lastSeenAt).toLocaleDateString()}</small></span>)}</div>}</section>;
}
