"use client";

import {useState} from "react";
import Link from "next/link";
import {Loading,Page} from "@/components/Page";
import {useData} from "@/components/DataProvider";
import {useLeagueDashboard} from "@/components/useLeagueDashboard";
import {useAwardsRace} from "@/components/useAwardsRace";

export default function WeeklyRecap(){
  const {data}=useData();const {dashboard,loading,power}=useLeagueDashboard(data);const {loading:awardsLoading,awards}=useAwardsRace();const [selectedWeek,setSelectedWeek]=useState(0);if(!data||loading||awardsLoading)return <Loading/>;
  if(!dashboard.available)return <Page title="Weekly League Recap" subtitle="The recap desk activates after the first Sleeper sync."><section className="liveEmpty"><h2>Waiting for live league data.</h2><Link href="/commissioner">Open Commissioner →</Link></section></Page>;
  if(!dashboard.completedWeek)return <Page title="Weekly League Recap" subtitle="Automatic matchup stories, weekly honors, and race movement begin after Week 1."><section className="recapPreseason"><span className="eyebrow">The newsroom is ready</span><h2>Opening night comes next.</h2><p>Once the first matchups are final, this page will publish five game stories, Player and Manager of the Week, the biggest upset, the closest finish, and movement across the league.</p><div><Link href="/live-league">View Live Dashboard →</Link><Link href="/league-awards">Preview Awards Race →</Link></div></section></Page>;
  const week=selectedWeek||dashboard.completedWeek;const games=dashboard.matchups.filter((game)=>game.week===week&&game.complete);const sorted=[...games].sort((a,b)=>Math.max(b.homePoints,b.awayPoints)-Math.max(a.homePoints,a.awayPoints));const top=sorted[0];const closest=[...games].sort((a,b)=>Math.abs(a.homePoints-a.awayPoints)-Math.abs(b.homePoints-b.awayPoints))[0];const upsets=games.filter((game)=>{const winner=game.homePoints>game.awayPoints?game.home:game.away,loser=winner===game.home?game.away:game.home;return winner.powerRank>loser.powerRank}).sort((a,b)=>{const aw=a.homePoints>a.awayPoints?a.home:a.away,al=aw===a.home?a.away:a.home,bw=b.homePoints>b.awayPoints?b.home:b.away,bl=bw===b.home?b.away:b.home;return (bw.powerRank-bl.powerRank)-(aw.powerRank-al.powerRank)});const upset=upsets[0];const weeklyPlayers=awards?.weeklyLeaders[String(week)]??[];const managerOfWeek=top?(top.homePoints>top.awayPoints?top.home:top.away):null;const headline=managerOfWeek?`${managerOfWeek.franchise} owns Week ${week}.`:`Week ${week} is in the books.`;
  const share=()=>navigator.clipboard?.writeText(`OKFL Week ${week}: ${headline} ${managerOfWeek?`${Math.max(top.homePoints,top.awayPoints).toFixed(1)} points led the league.`:""}`);
  return <Page title="Weekly League Recap" subtitle="Every matchup, the biggest moments, and the changing league picture—written automatically from Sleeper results.">
    <section className="recapToolbar"><div><label htmlFor="recap-week">Recap edition</label><select id="recap-week" value={week} onChange={(event)=>setSelectedWeek(Number(event.target.value))}>{Array.from({length:dashboard.completedWeek},(_,index)=>index+1).reverse().map((value)=><option value={value} key={value}>Week {value}</option>)}</select></div><button onClick={share}>Copy recap headline</button></section>
    <section className="recapHero"><div><span className="eyebrow">OKFL WEEK {week} · THE FINAL WORD</span><h2>{headline}</h2><p>{managerOfWeek?`${managerOfWeek.manager}'s team posted the week's biggest number and added another chapter to the 2026 race.`:"The league table shifted again."}</p></div><div><span>High score</span><b>{top?Math.max(top.homePoints,top.awayPoints).toFixed(1):"—"}</b><small>{managerOfWeek?.franchise??"No result"}</small></div></section>
    <section className="recapSuperlatives"><article><span>Player of the Week</span><b>{weeklyPlayers[0]?.name??"Pending"}</b><small>{weeklyPlayers[0]?`${weeklyPlayers[0].points.toFixed(1)} points · ${weeklyPlayers[0].franchise}`:"Player scoring unavailable"}</small></article><article><span>Closest finish</span><b>{closest?`${closest.home.franchise}–${closest.away.franchise}`:"Pending"}</b><small>{closest?`${Math.abs(closest.homePoints-closest.awayPoints).toFixed(2)}-point margin`:"No final"}</small></article><article><span>Biggest upset</span><b>{upset?(upset.homePoints>upset.awayPoints?upset.home.franchise:upset.away.franchise):"Favorites held"}</b><small>{upset?"Beat a higher-ranked opponent":"No power upset this week"}</small></article><article><span>Power leader</span><b>{power[0]?.franchise??"Pending"}</b><small>{power[0]?`${power[0].score} power score · ${power[0].movement>0?`up ${power[0].movement}`:"holding"}`:"No ranking"}</small></article></section>
    <div className="recapLayout"><section className="recapGames"><header><span className="eyebrow">Around the league</span><h2>{games.length} {games.length===1?"game":"games"}, {games.length} {games.length===1?"story":"stories"}</h2></header>{games.map((game)=>{const winner=game.homePoints>game.awayPoints?game.home:game.away,loser=winner===game.home?game.away:game.home,winningScore=Math.max(game.homePoints,game.awayPoints),losingScore=Math.min(game.homePoints,game.awayPoints),margin=winningScore-losingScore;return <article key={game.matchupId}><div><span>FINAL</span><b>{margin<5?"Instant classic":margin>30?"Statement win":"Business handled"}</b></div><h3>{winner.franchise} defeats {loser.franchise}</h3><p>{winner.manager}'s side scored {winningScore.toFixed(1)} and won by {margin.toFixed(1)}. {margin<5?"The matchup stayed alive until the final scoring swing.":margin>30?"It was one of the week's most decisive performances.":"A steady advantage proved enough by the final whistle."}</p><footer><strong>{winningScore.toFixed(1)}</strong><span>–</span><strong>{losingScore.toFixed(1)}</strong><Link href={`/franchises/${winner.franchiseId}`}>Winner profile →</Link></footer></article>})}</section>
      <aside className="recapRail"><section><span className="eyebrow">Top performers</span><h2>Player leaderboard</h2>{weeklyPlayers.slice(0,5).map((player)=><div key={player.playerId}><span>{player.rank}</span><div><b>{player.name}</b><small>{player.position} · {player.franchise}</small></div><strong>{player.points.toFixed(1)}</strong></div>)}</section><section><span className="eyebrow">Season impact</span><h2>The race after Week {week}</h2><p>{awards?.managerRaces[0]?.candidates[0]?.manager??"The leader"} currently leads Manager of the Year, while {awards?.playerRaces[0]?.candidates[0]?.name??"the scoring leader"} sits atop the MVP ballot.</p><Link href="/league-awards">Open full awards race →</Link></section></aside>
    </div>
  </Page>;
}
