import {NextResponse} from "next/server";
import {getAccountFromRequest} from "@/lib/accountServer";
import {normalizeRecap} from "@/lib/commissionerRecap";
import {createAdminSupabase} from "@/lib/supabaseServer";

async function commissioner(request:Request){const account=await getAccountFromRequest(request);return account?.role==="commissioner"&&!account.mustChangePassword?account:null}
function missing(error:any){return String(error?.code)==="42P01"||/commissioner_recaps/i.test(String(error?.message||""))&&/does not exist|schema cache/i.test(String(error?.message||""))}
function migration(){return NextResponse.json({error:"Run supabase/014_commissioner_recaps.sql in the Supabase SQL Editor, then reload this page.",migrationRequired:true},{status:503})}
async function audit(supabase:any,action:string,key:string,before:any,after:any){await supabase.from("commissioner_audit_log").insert({league_id:"okfl",season:2026,action,entity_type:"commissioner_recap",entity_key:key,before_data:before||null,after_data:after||null})}

export async function GET(request:Request){try{if(!await commissioner(request))return NextResponse.json({error:"Commissioner account required."},{status:403});const week=Number(new URL(request.url).searchParams.get("week")||0),supabase=createAdminSupabase();let query=supabase.from("commissioner_recaps").select("*").eq("league_id","okfl").eq("season",2026).order("week",{ascending:false});if(week)query=query.eq("week",week);const {data,error}=await query;if(error)throw error;return NextResponse.json({recaps:(data||[]).map(normalizeRecap)})}catch(error){if(missing(error))return migration();return NextResponse.json({error:error instanceof Error?error.message:"Could not load recap drafts."},{status:500})}}

export async function POST(request:Request){try{const account=await commissioner(request);if(!account)return NextResponse.json({error:"Commissioner account required."},{status:403});const body=await request.json(),recap=normalizeRecap(body.recap),action=String(body.action||"save");if(recap.headline.length<5||!recap.sections.length)return NextResponse.json({error:"Add a headline and at least one article section."},{status:400});const status=action==="publish"?"published":action==="unpublish"?"draft":recap.status;const supabase=createAdminSupabase(),now=new Date().toISOString(),payload={league_id:"okfl",season:2026,week:recap.week,status,headline:recap.headline,dek:recap.dek,quote:recap.quote,sections:recap.sections,updated_by:account.userId,updated_by_name:account.displayName,updated_at:now,published_at:status==="published"?(recap.publishedAt||now):null};const {data:before}=await supabase.from("commissioner_recaps").select("*").eq("league_id","okfl").eq("season",2026).eq("week",recap.week).maybeSingle();const {data,error}=await supabase.from("commissioner_recaps").upsert(payload,{onConflict:"league_id,season,week"}).select("*").single();if(error)throw error;await audit(supabase,status==="published"?"publish_weekly_recap":"save_weekly_recap",`2026-${recap.week}`,before,data);return NextResponse.json({ok:true,recap:normalizeRecap(data)})}catch(error){if(missing(error))return migration();return NextResponse.json({error:error instanceof Error?error.message:"Could not save recap."},{status:500})}}
