"use client";

import {useMemo,useState} from "react";
import Link from "next/link";
import {Page,Loading} from "@/components/Page";
import {useData} from "@/components/DataProvider";
import {useLeagueDashboard} from "@/components/useLeagueDashboard";
import {simulatePlayoffOdds} from "@/lib/liveLeague";

export default function PlayoffOdds(){
  const {data}=useData(); const {dashboard,loading}=useLeagueDashboard(data); const [iterations,setIterations]=useState(5000); const [boostTeam,setBoostTeam]=useState(""); const [boost,setBoost]=useState(0);
  const odds=useMemo(()=>simulatePlayoffOdds(dashboard,iterations,boostTeam,boost),[dashboard,iterations,boostTeam,boost]); if(!data||loading)return <Loading/>;
  if(!dashboard.available)return <Page title="Playoff Odds Simulator" subtitle="Run Sleeper Sync once to activate the 2026 playoff race."><section className="liveEmpty"><h2>Live season data required.</h2><Link href="/commissioner">Open Commissioner →</Link></section></Page>;
  const favorite=odds[0];
  return <Page title="Playoff Odds Simulator" subtitle="Simulate the remaining regular season and playoffs using live records, points, schedule, and current OKFL Power Rankings.">
    <section className="oddsHero"><div><span className="eyebrow">{iterations.toLocaleString()} season simulations · through Week {dashboard.completedWeek}</span><h2>{favorite?.franchise} has the inside track.</h2><p>Every run resolves the remaining schedule, applies points-based tiebreakers, seeds six playoff teams, and plays through the championship.</p></div><div><span>Playoff favorite</span><b>{favorite?.playoff.toFixed(1)}%</b><small>{favorite?.champion.toFixed(1)}% title chance</small></div></section>
    <section className="simControls"><div><label htmlFor="sim-count">Simulations</label><select id="sim-count" value={iterations} onChange={(event)=>setIterations(Number(event.target.value))}><option value={1000}>1,000 · Fast</option><option value={5000}>5,000 · Balanced</option><option value={10000}>10,000 · Precise</option></select></div><div><label htmlFor="boost-team">What-if team</label><select id="boost-team" value={boostTeam} onChange={(event)=>setBoostTeam(event.target.value)}><option value="">No adjustment</option>{dashboard.standings.map((team)=><option value={team.franchiseId} key={team.franchiseId}>{team.franchise}</option>)}</select></div><div className="boostControl"><label htmlFor="power-boost">Power adjustment <b>{boost>0?`+${boost}`:boost}</b></label><input id="power-boost" type="range" min="-10" max="15" step="1" value={boost} disabled={!boostTeam} onChange={(event)=>setBoost(Number(event.target.value))}/><small>Test injuries, trades, or a breakout without changing saved rankings.</small></div><button onClick={()=>{setBoostTeam("");setBoost(0);setIterations(5000)}}>Reset model</button></section>
    <div className="oddsLayout"><section className="oddsTable"><header><span>RK</span><span>FRANCHISE</span><span>PROJ. W</span><span>PLAYOFFS</span><span>BYE</span><span>#1 SEED</span><span>TITLE</span></header>{odds.map((team,index)=><article key={team.franchiseId}><span>{index+1}</span><div><Link href={`/franchises/${team.franchiseId}`}>{team.franchise}</Link><small>{dashboard.standings.find((row)=>row.franchiseId===team.franchiseId)?.wins}-{dashboard.standings.find((row)=>row.franchiseId===team.franchiseId)?.losses} current</small></div><strong>{team.projectedWins.toFixed(1)}</strong><div className="oddsMeter"><i><b style={{width:`${team.playoff}%`}}/></i><strong>{team.playoff.toFixed(1)}%</strong></div><span>{team.bye.toFixed(1)}%</span><span>{team.first.toFixed(1)}%</span><em>{team.champion.toFixed(1)}%</em></article>)}</section>
      <aside className="oddsNotes"><section><span className="eyebrow">Model inputs</span><h2>What drives the odds</h2><div><b>Live standings</b><small>Wins, losses, ties, and points from Sleeper</small></div><div><b>Complete schedule</b><small>Published matchups plus calibrated placeholders for any weeks Sleeper has not released</small></div><div><b>Team strength</b><small>Auto-updating OKFL Power Ranking score</small></div><div><b>{dashboard.completedWeek===0?"Preseason uncertainty":"Confidence ramp"}</b><small>{dashboard.completedWeek===0?"Historical power is intentionally compressed until the draft and real games provide stronger evidence":"Weekly confidence increases gradually as completed 2026 results replace the preseason prior"}</small></div><div><b>Playoff format</b><small>Six teams qualify; the top two receive byes</small></div></section><section><span className="eyebrow">Important</span><p>These are simulations, not guarantees. They become more predictive as real 2026 games replace the preseason baseline.</p></section></aside>
    </div>
  </Page>;
}
